-- Файл предназначен для хранение общеигровых фиксированных данных: например тип черка

-- ИД выбранной сложности игры
local DIFFICULTY = GetDifficulty();

-- NOTE: Почему то результат вычислений это 0 или 1, но при этом все равно корректно работает в условия
-- Маппинг сложности игры на черк
GAME_MODE = {
  -- Простой выбор (REKRUT)
  SIMPLE_CHOOSE = DIFFICULTY == DIFFICULTY_EASY,
  -- Черк матчапов (VOIN)
  MATCHUPS = DIFFICULTY == DIFFICULTY_NORMAL,
  -- Получерк (VETERAN)
  HALF = DIFFICULTY == DIFFICULTY_HARD,
  -- Микс черк (GEROI)
  MIX = DIFFICULTY == DIFFICULTY_HEROIC,
}

-- Кастомное перечисление рас, за неимением такого по умолчанию
RACES = {
  -- Орден Порядка
  HAVEN = 0,
  -- Инферно
  INFERNO = 1,
  -- Некрополис
  NECROPOLIS = 2,
  -- Лесной Союз
  SYLVAN = 3,
  -- Акадения Волшебства
  ACADEMY = 4,
  -- Лига Теней
  DUNGEON = 5,
  -- Северные Кланы
  FORTRESS = 6,
  -- Великая Орда
  STRONGHOLD = 7,
};

------------------ ГЕРОИ, ИСПОЛЬЗУЮЩИЕСЯ В КАРТЕ ------------------------
HEROES_BY_RACE = {
  [RACES.HAVEN] = {
	  { name = "Orrin",           txt = "haven/heroDugal.txt",    dsc = "/Text/Game/Heroes/Specializations/Haven/Archer_Commander/Description.txt",   [PLAYER_1] = {{ red_icon = "hero_1_1_1", blue_icon = "hero_1_1_2" },   { red_icon = "hero_1_1_5", blue_icon = "hero_1_1_6" }},            [PLAYER_2] = {{ red_icon = "hero_1_1_3", blue_icon = "hero_1_1_4" },   { red_icon = "hero_1_1_7", blue_icon = "hero_1_1_8" }} },
	  { name = "Sarge",           txt = "haven/heroAksel.txt",    dsc = "/Text/Game/Heroes/Specializations/Haven/Jouster/Description.txt",            [PLAYER_1] = {{ red_icon = "hero_2_1_1", blue_icon = "hero_2_1_2" },   { red_icon = "hero_2_1_5", blue_icon = "hero_2_1_6" }},            [PLAYER_2] = {{ red_icon = "hero_2_1_3", blue_icon = "hero_2_1_4" },   { red_icon = "hero_2_1_7", blue_icon = "hero_2_1_8" }} },
	  { name = "Mardigo",         txt = "haven/heroLaslo.txt",    dsc = "/Text/Game/Heroes/Specializations/Haven/Infantry_Commander/Description.txt", [PLAYER_1] = {{ red_icon = "hero_3_1_1", blue_icon = "hero_3_1_2" },   { red_icon = "hero_3_1_5", blue_icon = "hero_3_1_6" }},            [PLAYER_2] = {{ red_icon = "hero_3_1_3", blue_icon = "hero_3_1_4" },   { red_icon = "hero_3_1_7", blue_icon = "hero_3_1_8" }} },
	  { name = "Brem",            txt = "haven/heroRutger.txt",   dsc = "/Text/Game/Heroes/Specializations/Haven/Wanderer/Description.txt",           [PLAYER_1] = {{ red_icon = "hero_4_1_1", blue_icon = "hero_4_1_2" },   { red_icon = "hero_4_1_5", blue_icon = "hero_4_1_6" }},            [PLAYER_2] = {{ red_icon = "hero_4_1_3", blue_icon = "hero_4_1_4" },   { red_icon = "hero_4_1_7", blue_icon = "hero_4_1_8" }} },
	  { name = "Maeve",           txt = "haven/heroMiv.txt",      dsc = "/Text/Game/Heroes/Specializations/Haven/Expediter/Description.txt",          [PLAYER_1] = {{ red_icon = "hero_5_1_1", blue_icon = "hero_5_1_2" },   { red_icon = "hero_5_1_5", blue_icon = "hero_5_1_6" }},            [PLAYER_2] = {{ red_icon = "hero_5_1_3", blue_icon = "hero_5_1_4" },   { red_icon = "hero_5_1_7", blue_icon = "hero_5_1_8" }} },
	  { name = "Ving",            txt = "haven/heroAiris.txt",    dsc = "/Text/Game/Heroes/Specializations/Haven/Griffon_Commander/Description.txt",  [PLAYER_1] = {{ red_icon = "hero_6_1_1", blue_icon = "hero_6_1_2" },   { red_icon = "hero_6_1_5", blue_icon = "hero_6_1_6" }},            [PLAYER_2] = {{ red_icon = "hero_6_1_3", blue_icon = "hero_6_1_4" },   { red_icon = "hero_6_1_7", blue_icon = "hero_6_1_8" }} },
	  { name = "Nathaniel",       txt = "haven/heroEllaina.txt",  dsc = "/Text/Game/Heroes/Specializations/Haven/Squire/Description.txt",             [PLAYER_1] = {{ red_icon = "hero_7_1_1", blue_icon = "hero_7_1_2" },   { red_icon = "hero_7_1_5", blue_icon = "hero_7_1_6" }},            [PLAYER_2] = {{ red_icon = "hero_7_1_3", blue_icon = "hero_7_1_4" },   { red_icon = "hero_7_1_7", blue_icon = "hero_7_1_8" }} },
	  { name = "Christian",       txt = "haven/heroVittorio.txt", dsc = "/Text/Game/Heroes/Specializations/Haven/Artilleryman/Description.txt",       [PLAYER_1] = {{ red_icon = "hero_8_1_1", blue_icon = "hero_8_1_2" },   { red_icon = "hero_8_1_5", blue_icon = "hero_8_1_6" }},            [PLAYER_2] = {{ red_icon = "hero_8_1_3", blue_icon = "hero_8_1_4" },   { red_icon = "hero_8_1_7", blue_icon = "hero_8_1_8" }} },
	  { name = "Godric",          txt = "haven/heroGodric.txt",   dsc = "/Text/Game/Heroes/Specializations/Haven/White_Knight/Description.txt",       [PLAYER_1] = {{ red_icon = "hero_9_1_1", blue_icon = "hero_9_1_2" },   { red_icon = "hero_9_1_5", blue_icon = "hero_9_1_6" }},            [PLAYER_2] = {{ red_icon = "hero_9_1_3", blue_icon = "hero_9_1_4" },   { red_icon = "hero_9_1_7", blue_icon = "hero_9_1_8" }} },
    { name = "RedHeavenHero03", txt = "haven/heroValeria.txt",  dsc = "/Text/Game/Heroes/Specializations/Haven/SpecValeria/Description.txt",        [PLAYER_1] = {{ red_icon = "hero_13_1_1", blue_icon = "hero_13_1_2" }, { red_icon = "hero_13_1_5", blue_icon = "hero_13_1_6" }},          [PLAYER_2] = {{ red_icon = "hero_13_1_3", blue_icon = "hero_13_1_4" }, { red_icon = "hero_13_1_7", blue_icon = "hero_13_1_8" }} },
--	  { name = "Isabell_A1",      txt = "haven/heroIsabel.txt",   p1 = "hero_11_1_1", p2 = "hero_11_1_2", p3 = "hero_11_1_3", p4 = "hero_11_1_4", dsc = "/Text/Game/Heroes/Specializations/Haven/Archer_Commander/Description.txt"},
--	  { name = "Duncan",          txt = "haven/heroDuncan.txt",   p1 = "hero_12_1_1", p2 = "hero_12_1_2", p3 = "hero_12_1_3", p4 = "hero_12_1_4", dsc = "/Text/Game/Heroes/Specializations/Haven/Archer_Commander/Description.txt"},
--    { name = "Nicolai",         txt = "haven/heroNicolai.txt",  p1 = "hero_10_1_1", p2 = "hero_10_1_2", p3 = "hero_10_1_3", p4 = "hero_10_1_4", dsc = "/Text/Game/Heroes/Specializations/Haven/Archer_Commander/Description.txt"}
  },
  [RACES.INFERNO] = {
	  { name = "Grok",        txt = "inferno/heroGrok.txt",       dsc = "/Text/Game/Heroes/Specializations/Inferno/Beater/Description.txt",                [PLAYER_1] = {{ red_icon = "hero_1_2_1", blue_icon = "hero_1_2_2" },   { red_icon = "hero_1_2_5", blue_icon = "hero_1_2_6" }},            [PLAYER_2] = {{ red_icon = "hero_1_2_3", blue_icon = "hero_1_2_4" },   { red_icon = "hero_1_2_7", blue_icon = "hero_1_2_8" }} },
	  { name = "Oddrema",     txt = "inferno/heroDgezebet.txt",   dsc = "/Text/Game/Heroes/Specializations/Inferno/Temptress/Description.txt",             [PLAYER_1] = {{ red_icon = "hero_2_2_1", blue_icon = "hero_2_2_2" },   { red_icon = "hero_2_2_5", blue_icon = "hero_2_2_6" }},            [PLAYER_2] = {{ red_icon = "hero_2_2_3", blue_icon = "hero_2_2_4" },   { red_icon = "hero_2_2_7", blue_icon = "hero_2_2_8" }} },
    { name = "Marder",      txt = "inferno/heroMarbas.txt",     dsc = "/Text/Game/Heroes/Specializations/Inferno/Impregnable/Description.txt",           [PLAYER_1] = {{ red_icon = "hero_3_2_1", blue_icon = "hero_3_2_2" },   { red_icon = "hero_3_2_5", blue_icon = "hero_3_2_6" }},            [PLAYER_2] = {{ red_icon = "hero_3_2_3", blue_icon = "hero_3_2_4" },   { red_icon = "hero_3_2_7", blue_icon = "hero_3_2_8" }} },
	  { name = "Jazaz",       txt = "inferno/heroNibros.txt",     dsc = "/Text/Game/Heroes/Specializations/Inferno/Flagbearer_of_Darkness/Description.txt",[PLAYER_1] = {{ red_icon = "hero_4_2_1", blue_icon = "hero_4_2_2" },   { red_icon = "hero_4_2_5", blue_icon = "hero_4_2_6" }},            [PLAYER_2] = {{ red_icon = "hero_4_2_3", blue_icon = "hero_4_2_4" },   { red_icon = "hero_4_2_7", blue_icon = "hero_4_2_8" }} },
	  { name = "Efion",       txt = "inferno/heroAlastor.txt",    dsc = "/Text/Game/Heroes/Specializations/Inferno/Hypnotist/Description.txt",             [PLAYER_1] = {{ red_icon = "hero_5_2_1", blue_icon = "hero_5_2_2" },   { red_icon = "hero_5_2_5", blue_icon = "hero_5_2_6" }},            [PLAYER_2] = {{ red_icon = "hero_5_2_3", blue_icon = "hero_5_2_4" },   { red_icon = "hero_5_2_7", blue_icon = "hero_5_2_8" }} },
	  { name = "Deleb",       txt = "inferno/heroDeleb.txt",      dsc = "/Text/Game/Heroes/Specializations/Inferno/Bombardier/Description.txt",            [PLAYER_1] = {{ red_icon = "hero_6_2_1", blue_icon = "hero_6_2_2" },   { red_icon = "hero_6_2_5", blue_icon = "hero_6_2_6" }},            [PLAYER_2] = {{ red_icon = "hero_6_2_3", blue_icon = "hero_6_2_4" },   { red_icon = "hero_6_2_7", blue_icon = "hero_6_2_8" }} },
	  { name = "Calid",       txt = "inferno/heroGrol.txt",       dsc = "/Text/Game/Heroes/Specializations/Inferno/Breeder/Description.txt",               [PLAYER_1] = {{ red_icon = "hero_7_2_1", blue_icon = "hero_7_2_2" },   { red_icon = "hero_7_2_5", blue_icon = "hero_7_2_6" }},            [PLAYER_2] = {{ red_icon = "hero_7_2_3", blue_icon = "hero_7_2_4" },   { red_icon = "hero_7_2_7", blue_icon = "hero_7_2_8" }} },
	  { name = "Nymus",       txt = "inferno/heroNimus.txt",      dsc = "/Text/Game/Heroes/Specializations/Inferno/Gate_Keeper/Description.txt",           [PLAYER_1] = {{ red_icon = "hero_8_2_1", blue_icon = "hero_8_2_2" },   { red_icon = "hero_8_2_5", blue_icon = "hero_8_2_6" }},            [PLAYER_2] = {{ red_icon = "hero_8_2_3", blue_icon = "hero_8_2_4" },   { red_icon = "hero_8_2_7", blue_icon = "hero_8_2_8" }} },
	  { name = "Orlando",     txt = "inferno/heroOrlando.txt",    dsc = "/Text/Game/Heroes/Specializations/Inferno/SpecOrlando/Description.txt",           [PLAYER_1] = {{ red_icon = "hero_9_2_1", blue_icon = "hero_9_2_2" },   { red_icon = "hero_9_2_5", blue_icon = "hero_9_2_6" }},            [PLAYER_2] = {{ red_icon = "hero_9_2_3", blue_icon = "hero_9_2_4" },   { red_icon = "hero_9_2_7", blue_icon = "hero_9_2_8" }} },
	  { name = "Agrael",      txt = "inferno/heroAgrail.txt",     dsc = "/Text/Game/Heroes/Specializations/Inferno/SpecAgrael/Description.txt",            [PLAYER_1] = {{ red_icon = "hero_10_2_1", blue_icon = "hero_10_2_2" }, { red_icon = "hero_10_2_5", blue_icon = "hero_10_2_6" }},          [PLAYER_2] = {{ red_icon = "hero_10_2_3", blue_icon = "hero_10_2_4" }, { red_icon = "hero_10_2_7", blue_icon = "hero_10_2_8" }} },
--	  { name = "Kha-Beleth",  txt = "inferno/heroVlastelin.txt",  dsc = "/Text/Game/Heroes/Specializations/Inferno/Beater/Description.txt",                [PLAYER_1] = { red_icon = "hero_11_2_1", blue_icon = "hero_11_2_2" }, [PLAYER_2] = { red_icon = "hero_11_2_3", blue_icon = "hero_11_2_4" } }
  },
  [RACES.NECROPOLIS] = {
	  { name = "Nemor",       txt = "necropolis/heroDeidra.txt",     dsc = "/Text/Game/Heroes/Specializations/Necropolis/Dark_Emissary/Description.txt",     [PLAYER_1] = {{ red_icon = "hero_1_3_1", blue_icon = "hero_1_3_2" },   { red_icon = "hero_1_3_5", blue_icon = "hero_1_3_6" }},   [PLAYER_2] = {{ red_icon = "hero_1_3_3", blue_icon = "hero_1_3_4" },   { red_icon = "hero_1_3_7", blue_icon = "hero_1_3_8" }} },
	  { name = "Tamika",      txt = "necropolis/heroLukrecia.txt",   dsc = "/Text/Game/Heroes/Specializations/Necropolis/Vamipre_Princess/Description.txt",  [PLAYER_1] = {{ red_icon = "hero_2_3_1", blue_icon = "hero_2_3_2" },   { red_icon = "hero_2_3_5", blue_icon = "hero_2_3_6" }},   [PLAYER_2] = {{ red_icon = "hero_2_3_3", blue_icon = "hero_2_3_4" },   { red_icon = "hero_2_3_7", blue_icon = "hero_2_3_8" }} },
	  { name = "Muscip",      txt = "necropolis/heroNaadir.txt",     dsc = "/Text/Game/Heroes/Specializations/Necropolis/Soulhunter/Description.txt",        [PLAYER_1] = {{ red_icon = "hero_3_3_1", blue_icon = "hero_3_3_2" },   { red_icon = "hero_3_3_5", blue_icon = "hero_3_3_6" }},   [PLAYER_2] = {{ red_icon = "hero_3_3_3", blue_icon = "hero_3_3_4" },   { red_icon = "hero_3_3_7", blue_icon = "hero_3_3_8" }} },
	  { name = "Aberrar",     txt = "necropolis/heroZoltan.txt",     dsc = "/Text/Game/Heroes/Specializations/Necropolis/Mind_Cleaner/Description.txt",      [PLAYER_1] = {{ red_icon = "hero_4_3_1", blue_icon = "hero_4_3_2" },   { red_icon = "hero_4_3_5", blue_icon = "hero_4_3_6" }},   [PLAYER_2] = {{ red_icon = "hero_4_3_3", blue_icon = "hero_4_3_4" },   { red_icon = "hero_4_3_7", blue_icon = "hero_4_3_8" }} },
	  { name = "Straker",     txt = "necropolis/heroOrson.txt",      dsc = "/Text/Game/Heroes/Specializations/Necropolis/Zombie_Leader/Description.txt",     [PLAYER_1] = {{ red_icon = "hero_5_3_1", blue_icon = "hero_5_3_2" },   { red_icon = "hero_5_3_5", blue_icon = "hero_5_3_6" }},   [PLAYER_2] = {{ red_icon = "hero_5_3_3", blue_icon = "hero_5_3_4" },   { red_icon = "hero_5_3_7", blue_icon = "hero_5_3_8" }} },
	  { name = "Effig",       txt = "necropolis/heroRavenna.txt",    dsc = "/Text/Game/Heroes/Specializations/Necropolis/Maledictor/Description.txt",        [PLAYER_1] = {{ red_icon = "hero_6_3_1", blue_icon = "hero_6_3_2" },   { red_icon = "hero_6_3_5", blue_icon = "hero_6_3_6" }},   [PLAYER_2] = {{ red_icon = "hero_6_3_3", blue_icon = "hero_6_3_4" },   { red_icon = "hero_6_3_7", blue_icon = "hero_6_3_8" }} },
	  { name = "Pelt",        txt = "necropolis/heroVlad.txt",       dsc = "/Text/Game/Heroes/Specializations/Necropolis/Reanimator/Description.txt",        [PLAYER_1] = {{ red_icon = "hero_7_3_1", blue_icon = "hero_7_3_2" },   { red_icon = "hero_7_3_5", blue_icon = "hero_7_3_6" }},   [PLAYER_2] = {{ red_icon = "hero_7_3_3", blue_icon = "hero_7_3_4" },   { red_icon = "hero_7_3_7", blue_icon = "hero_7_3_8" }} },
	  { name = "Gles",        txt = "necropolis/heroKaspar.txt",     dsc = "/Text/Game/Heroes/Specializations/Necropolis/Empiric/Description.txt",           [PLAYER_1] = {{ red_icon = "hero_8_3_1", blue_icon = "hero_8_3_2" },   { red_icon = "hero_8_3_5", blue_icon = "hero_8_3_6" }},   [PLAYER_2] = {{ red_icon = "hero_8_3_3", blue_icon = "hero_8_3_4" },   { red_icon = "hero_8_3_7", blue_icon = "hero_8_3_8" }} },
	  { name = "Arantir",     txt = "necropolis/heroArantir.txt",    dsc = "/Text/Game/Heroes/Specializations/Necropolis/AvatarOfDeath/Description.txt",     [PLAYER_1] = {{ red_icon = "hero_9_3_1", blue_icon = "hero_9_3_2" },   { red_icon = "hero_9_3_5", blue_icon = "hero_9_3_6" }},   [PLAYER_2] = {{ red_icon = "hero_9_3_3", blue_icon = "hero_9_3_4" },   { red_icon = "hero_9_3_7", blue_icon = "hero_9_3_8" }} },
	  { name = "OrnellaNecro",txt = "necropolis/heroOrnella.txt",    dsc = "/Text/Game/Heroes/Specializations/Necropolis/SpecOrnella/Description.txt",       [PLAYER_1] = {{ red_icon = "hero_10_3_1", blue_icon = "hero_10_3_2" }, { red_icon = "hero_10_3_5", blue_icon = "hero_10_3_6" }}, [PLAYER_2] = {{ red_icon = "hero_10_3_3", blue_icon = "hero_10_3_4" }, { red_icon = "hero_10_3_7", blue_icon = "hero_10_3_8" }} },
    { name = "Berein",      txt = "necropolis/heroMarkel.txt",     dsc = "/Text/Game/Heroes/Specializations/Necropolis/Heir_of_Undeath/Berein.txt",        [PLAYER_1] = {{ red_icon = "hero_11_3_1", blue_icon = "hero_11_3_2" }, { red_icon = "hero_11_3_5", blue_icon = "hero_11_3_6" }}, [PLAYER_2] = {{ red_icon = "hero_11_3_3", blue_icon = "hero_11_3_4" }, { red_icon = "hero_11_3_7", blue_icon = "hero_11_3_8" }} },
    { name = "Nikolas",     txt = "necropolis/heroNikolas.txt",    dsc = "/Text/Game/Heroes/Specializations/Necropolis/SpecNikolas/Description.txt",       [PLAYER_1] = {{ red_icon = "hero_12_3_1", blue_icon = "hero_12_3_2" }, { red_icon = "hero_12_3_5", blue_icon = "hero_12_3_6" }}, [PLAYER_2] = {{ red_icon = "hero_12_3_3", blue_icon = "hero_12_3_4" }, { red_icon = "hero_12_3_7", blue_icon = "hero_12_3_8" }} }
  },
  [RACES.SYLVAN] = {
	  { name = "Metlirn",     txt = "sylvan/heroAnven.txt",      dsc = "/Text/Game/Heroes/Specializations/Preserve/Forest_Guardian/Description.txt",  [PLAYER_1] = {{ red_icon = "hero_1_4_1", blue_icon = "hero_1_4_2" },   { red_icon = "hero_1_4_5", blue_icon = "hero_1_4_6" }}, [PLAYER_2] = {{ red_icon = "hero_1_4_3", blue_icon = "hero_1_4_4" },   { red_icon = "hero_1_4_7", blue_icon = "hero_1_4_8" }} },
	  { name = "Gillion",     txt = "sylvan/heroGilraen.txt",    dsc = "/Text/Game/Heroes/Specializations/Preserve/Blade_Master/Description.txt",     [PLAYER_1] = {{ red_icon = "hero_2_4_1", blue_icon = "hero_2_4_2" },   { red_icon = "hero_2_4_5", blue_icon = "hero_2_4_6" }}, [PLAYER_2] = {{ red_icon = "hero_2_4_3", blue_icon = "hero_2_4_4" },   { red_icon = "hero_2_4_7", blue_icon = "hero_2_4_8" }}  },
	  { name = "Nadaur",      txt = "sylvan/heroTalanar.txt",    dsc = "/Text/Game/Heroes/Specializations/Preserve/Elven_Fury/Description.txt",       [PLAYER_1] = {{ red_icon = "hero_3_4_1", blue_icon = "hero_3_4_2" },   { red_icon = "hero_3_4_5", blue_icon = "hero_3_4_6" }}, [PLAYER_2] = {{ red_icon = "hero_3_4_3", blue_icon = "hero_3_4_4" },   { red_icon = "hero_3_4_7", blue_icon = "hero_3_4_8" }}  },
	  { name = "Diraya",      txt = "sylvan/heroDirael.txt",     dsc = "/Text/Game/Heroes/Specializations/Preserve/Call_of_the_Wasp/Description.txt", [PLAYER_1] = {{ red_icon = "hero_4_4_1", blue_icon = "hero_4_4_2" },   { red_icon = "hero_4_4_5", blue_icon = "hero_4_4_6" }}, [PLAYER_2] = {{ red_icon = "hero_4_4_3", blue_icon = "hero_4_4_4" },   { red_icon = "hero_4_4_7", blue_icon = "hero_4_4_8" }}  },
	  { name = "Ossir",       txt = "sylvan/heroOssir.txt",      dsc = "/Text/Game/Heroes/Specializations/Preserve/Hunter/Description.txt",           [PLAYER_1] = {{ red_icon = "hero_5_4_1", blue_icon = "hero_5_4_2" },   { red_icon = "hero_5_4_5", blue_icon = "hero_5_4_6" }}, [PLAYER_2] = {{ red_icon = "hero_5_4_3", blue_icon = "hero_5_4_4" },   { red_icon = "hero_5_4_7", blue_icon = "hero_5_4_8" }}  },
	  { name = "Itil",        txt = "sylvan/heroIlfina.txt",     dsc = "/Text/Game/Heroes/Specializations/Preserve/Unicorn_Trainer/Description.txt",  [PLAYER_1] = {{ red_icon = "hero_6_4_1", blue_icon = "hero_6_4_2" },   { red_icon = "hero_6_4_5", blue_icon = "hero_6_4_6" }}, [PLAYER_2] = {{ red_icon = "hero_6_4_3", blue_icon = "hero_6_4_4" },   { red_icon = "hero_6_4_7", blue_icon = "hero_6_4_8" }}  },
	  { name = "Elleshar",    txt = "sylvan/heroVinrael.txt",    dsc = "/Text/Game/Heroes/Specializations/Preserve/Talented_Warrior/Description.txt", [PLAYER_1] = {{ red_icon = "hero_7_4_1", blue_icon = "hero_7_4_2" },   { red_icon = "hero_7_4_5", blue_icon = "hero_7_4_6" }}, [PLAYER_2] = {{ red_icon = "hero_7_4_3", blue_icon = "hero_7_4_4" },   { red_icon = "hero_7_4_7", blue_icon = "hero_7_4_8" }}  },
	  { name = "Linaas",      txt = "sylvan/heroVingael.txt",    dsc = "/Text/Game/Heroes/Specializations/Preserve/Waylayer/Description.txt",         [PLAYER_1] = {{ red_icon = "hero_8_4_1", blue_icon = "hero_8_4_2" },   { red_icon = "hero_8_4_5", blue_icon = "hero_8_4_6" }}, [PLAYER_2] = {{ red_icon = "hero_8_4_3", blue_icon = "hero_8_4_4" },   { red_icon = "hero_8_4_7", blue_icon = "hero_8_4_8" }}  },
	  { name = "Heam",        txt = "sylvan/heroFaidaen.txt",    dsc = "/Text/Game/Heroes/Specializations/Preserve/Elven_Volley/Description.txt",     [PLAYER_1] = {{ red_icon = "hero_9_4_1", blue_icon = "hero_9_4_2" },   { red_icon = "hero_9_4_5", blue_icon = "hero_9_4_6" }}, [PLAYER_2] = {{ red_icon = "hero_9_4_3", blue_icon = "hero_9_4_4" },   { red_icon = "hero_9_4_7", blue_icon = "hero_9_4_8" }}  },
	  { name = "Ildar",       txt = "sylvan/heroAlaron.txt",     dsc = "/Text/Game/Heroes/Specializations/Preserve/SpecIldar/Description.txt",        [PLAYER_1] = {{ red_icon = "hero_10_4_1", blue_icon = "hero_10_4_2" }, { red_icon = "hero_10_4_5", blue_icon = "hero_10_4_6" }}, [PLAYER_2] = {{ red_icon = "hero_10_4_3", blue_icon = "hero_10_4_4" }, { red_icon = "hero_10_4_7", blue_icon = "hero_10_4_8" }}  },
--	  { name = "GhostFSLord", txt = "sylvan/heroPrizrak.txt",    dsc = "/Text/Game/Heroes/Specializations/Preserve/Forest_Guardian/Description.txt",  [PLAYER_1] = { red_icon = "hero_11_4_1", blue_icon = "hero_11_4_2" }, [PLAYER_2] = { red_icon = "hero_11_4_3", blue_icon = "hero_11_4_4" }  }
  },
  [RACES.ACADEMY] = {
	  { name = "Faiz",        txt = "academy/heroFaiz.txt",       dsc = "/Text/Game/Heroes/Specializations/Academy/Disrupter/Description.txt",          [PLAYER_1] = {{ red_icon = "hero_1_5_1", blue_icon = "hero_1_5_2" },   { red_icon = "hero_1_5_5", blue_icon = "hero_1_5_6" }}, [PLAYER_2] = {{ red_icon = "hero_1_5_3", blue_icon = "hero_1_5_4" }, { red_icon = "hero_1_5_7", blue_icon = "hero_1_5_8" }} },
	  { name = "Havez",       txt = "academy/heroHafiz.txt",      dsc = "/Text/Game/Heroes/Specializations/Academy/Artisan/Description.txt",            [PLAYER_1] = {{ red_icon = "hero_2_5_1", blue_icon = "hero_2_5_2" },   { red_icon = "hero_2_5_5", blue_icon = "hero_2_5_6" }}, [PLAYER_2] = {{ red_icon = "hero_2_5_3", blue_icon = "hero_2_5_4" }, { red_icon = "hero_2_5_7", blue_icon = "hero_2_5_8" }} },
	  { name = "Nur",         txt = "academy/heroNazir.txt",      dsc = "/Text/Game/Heroes/Specializations/Academy/Weilder_of_Fire/Description.txt",    [PLAYER_1] = {{ red_icon = "hero_3_5_1", blue_icon = "hero_3_5_2" },   { red_icon = "hero_3_5_5", blue_icon = "hero_3_5_6" }}, [PLAYER_2] = {{ red_icon = "hero_3_5_3", blue_icon = "hero_3_5_4" }, { red_icon = "hero_3_5_7", blue_icon = "hero_3_5_8" }} },
	  { name = "Astral",      txt = "academy/heroNura.txt",       dsc = "/Text/Game/Heroes/Specializations/Academy/Inexhaustible/Description.txt",      [PLAYER_1] = {{ red_icon = "hero_4_5_1", blue_icon = "hero_4_5_2" },   { red_icon = "hero_4_5_5", blue_icon = "hero_4_5_6" }}, [PLAYER_2] = {{ red_icon = "hero_4_5_3", blue_icon = "hero_4_5_4" }, { red_icon = "hero_4_5_7", blue_icon = "hero_4_5_8" }} },
	  { name = "Sufi",        txt = "academy/heroOra.txt",        dsc = "/Text/Game/Heroes/Specializations/Academy/Feather_Mage/Description.txt",       [PLAYER_1] = {{ red_icon = "hero_5_5_1", blue_icon = "hero_5_5_2" },   { red_icon = "hero_5_5_5", blue_icon = "hero_5_5_6" }}, [PLAYER_2] = {{ red_icon = "hero_5_5_3", blue_icon = "hero_5_5_4" }, { red_icon = "hero_5_5_7", blue_icon = "hero_5_5_8" }} },
	  { name = "Razzak",      txt = "academy/heroNarhiz.txt",     dsc = "/Text/Game/Heroes/Specializations/Academy/Mentor/Description.txt",             [PLAYER_1] = {{ red_icon = "hero_6_5_1", blue_icon = "hero_6_5_2" },   { red_icon = "hero_6_5_5", blue_icon = "hero_6_5_6" }}, [PLAYER_2] = {{ red_icon = "hero_6_5_3", blue_icon = "hero_6_5_4" }, { red_icon = "hero_6_5_7", blue_icon = "hero_6_5_8" }} },
	  { name = "Tan",         txt = "academy/heroDgalib.txt",     dsc = "/Text/Game/Heroes/Specializations/Academy/Radiant/Description.txt",            [PLAYER_1] = {{ red_icon = "hero_7_5_1", blue_icon = "hero_7_5_2" },   { red_icon = "hero_7_5_5", blue_icon = "hero_7_5_6" }}, [PLAYER_2] = {{ red_icon = "hero_7_5_3", blue_icon = "hero_7_5_4" }, { red_icon = "hero_7_5_7", blue_icon = "hero_7_5_8" }} },
	  { name = "Isher",       txt = "academy/heroRazzak.txt",     dsc = "/Text/Game/Heroes/Specializations/Academy/Machinist/Description.txt",          [PLAYER_1] = {{ red_icon = "hero_8_5_1", blue_icon = "hero_8_5_2" },   { red_icon = "hero_8_5_5", blue_icon = "hero_8_5_6" }}, [PLAYER_2] = {{ red_icon = "hero_8_5_3", blue_icon = "hero_8_5_4" }, { red_icon = "hero_8_5_7", blue_icon = "hero_8_5_8" }} },
	  { name = "Zehir",       txt = "academy/heroZehir.txt",      dsc = "/Text/Game/Heroes/Specializations/Academy/Master_of_Elements/Description.txt", [PLAYER_1] = {{ red_icon = "hero_9_5_1", blue_icon = "hero_9_5_2" },   { red_icon = "hero_9_5_5", blue_icon = "hero_9_5_6" }}, [PLAYER_2] = {{ red_icon = "hero_9_5_3", blue_icon = "hero_9_5_4" }, { red_icon = "hero_9_5_7", blue_icon = "hero_9_5_8" }} },
	  { name = "Maahir",      txt = "academy/heroMaahir.txt",     dsc = "/Text/Game/Heroes/Specializations/Academy/SpecMaahir/Description.txt",         [PLAYER_1] = {{ red_icon = "hero_10_5_1", blue_icon = "hero_10_5_2" }, { red_icon = "hero_10_5_5", blue_icon = "hero_10_5_6" }}, [PLAYER_2] = {{ red_icon = "hero_10_5_3", blue_icon = "hero_10_5_4" }, { red_icon = "hero_10_5_7", blue_icon = "hero_10_5_8" }} },
--	  { name = "Cyrus",       txt = "academy/heroSairus.txt",     dsc = "/Text/Game/Heroes/Specializations/Academy/SpecCyrus/Description.txt",          [PLAYER_1] = { red_icon = "hero_11_5_1", blue_icon = "hero_11_5_2" }, [PLAYER_2] = { red_icon = "hero_11_5_3", blue_icon = "hero_11_5_4" } }
  },
  [RACES.DUNGEON] = {
	  { name = "Eruina",      txt = "dungeon/heroErin.txt",       dsc = "/Text/Game/Heroes/Specializations/Dungeon/Matron_Salvo/Description.txt",           [PLAYER_1] = {{ red_icon = "hero_1_6_1", blue_icon = "hero_1_6_2" }, { red_icon = "hero_1_6_5", blue_icon = "hero_1_6_6" }}, [PLAYER_2] = {{ red_icon = "hero_1_6_3", blue_icon = "hero_1_6_4" }, { red_icon = "hero_1_6_7", blue_icon = "hero_1_6_8" }} },
	  { name = "Inagost",     txt = "dungeon/heroSinitar.txt",    dsc = "/Text/Game/Heroes/Specializations/Dungeon/Power_Bargain/Description.txt",          [PLAYER_1] = {{ red_icon = "hero_2_6_1", blue_icon = "hero_2_6_2" }, { red_icon = "hero_2_6_5", blue_icon = "hero_2_6_6" }}, [PLAYER_2] = {{ red_icon = "hero_2_6_3", blue_icon = "hero_2_6_4" }, { red_icon = "hero_2_6_7", blue_icon = "hero_2_6_8" }} },
	  { name = "Urunir",      txt = "dungeon/heroIranna.txt",     dsc = "/Text/Game/Heroes/Specializations/Dungeon/Seducer/Description.txt",                [PLAYER_1] = {{ red_icon = "hero_3_6_1", blue_icon = "hero_3_6_2" }, { red_icon = "hero_3_6_5", blue_icon = "hero_3_6_6" }}, [PLAYER_2] = {{ red_icon = "hero_3_6_3", blue_icon = "hero_3_6_4" }, { red_icon = "hero_3_6_7", blue_icon = "hero_3_6_8" }} },
	  { name = "Almegir",     txt = "dungeon/heroIrbet.txt",      dsc = "/Text/Game/Heroes/Specializations/Dungeon/Dark_Acolyte/Description.txt",           [PLAYER_1] = {{ red_icon = "hero_4_6_1", blue_icon = "hero_4_6_2" }, { red_icon = "hero_4_6_5", blue_icon = "hero_4_6_6" }}, [PLAYER_2] = {{ red_icon = "hero_4_6_3", blue_icon = "hero_4_6_4" }, { red_icon = "hero_4_6_7", blue_icon = "hero_4_6_8" }} },
	  { name = "Menel",       txt = "dungeon/heroKifra.txt",      dsc = "/Text/Game/Heroes/Specializations/Dungeon/Slaveholder/Description.txt",            [PLAYER_1] = {{ red_icon = "hero_5_6_1", blue_icon = "hero_5_6_2" }, { red_icon = "hero_5_6_5", blue_icon = "hero_5_6_6" }}, [PLAYER_2] = {{ red_icon = "hero_5_6_3", blue_icon = "hero_5_6_4" }, { red_icon = "hero_5_6_7", blue_icon = "hero_5_6_8" }} },
	  { name = "Dalom",       txt = "dungeon/heroLetos.txt",      dsc = "/Text/Game/Heroes/Specializations/Dungeon/Poisoner/Description.txt",               [PLAYER_1] = {{ red_icon = "hero_6_6_1", blue_icon = "hero_6_6_2" }, { red_icon = "hero_6_6_5", blue_icon = "hero_6_6_6" }}, [PLAYER_2] = {{ red_icon = "hero_6_6_3", blue_icon = "hero_6_6_4" }, { red_icon = "hero_6_6_7", blue_icon = "hero_6_6_8" }} },
	  { name = "Ferigl",      txt = "dungeon/heroSorgal.txt",     dsc = "/Text/Game/Heroes/Specializations/Dungeon/Lizard_Breeder/Description.txt",         [PLAYER_1] = {{ red_icon = "hero_7_6_1", blue_icon = "hero_7_6_2" }, { red_icon = "hero_7_6_5", blue_icon = "hero_7_6_6" }}, [PLAYER_2] = {{ red_icon = "hero_7_6_3", blue_icon = "hero_7_6_4" }, { red_icon = "hero_7_6_7", blue_icon = "hero_7_6_8" }} },
	  { name = "Ohtarig",     txt = "dungeon/heroVaishan.txt",    dsc = "/Text/Game/Heroes/Specializations/Dungeon/Savage/Description.txt",                 [PLAYER_1] = {{ red_icon = "hero_8_6_1", blue_icon = "hero_8_6_2" }, { red_icon = "hero_8_6_5", blue_icon = "hero_8_6_6" }}, [PLAYER_2] = {{ red_icon = "hero_8_6_3", blue_icon = "hero_8_6_4" }, { red_icon = "hero_8_6_7", blue_icon = "hero_8_6_8" }} },
--	  { name = "Raelag_A1",   txt = "dungeon/heroRailag.txt",     dsc = "/Text/Game/Heroes/Specializations/Dungeon/MasterOfInitiative/Description.txt",     [PLAYER_1] = { red_icon = "hero_9_6_1", blue_icon = "hero_9_6_2" }, [PLAYER_2] = { red_icon = "hero_9_6_3", blue_icon = "hero_9_6_4" } },
	  { name = "Kelodin",     txt = "dungeon/heroShadia.txt",     dsc = "/Text/Game/Heroes/Specializations/Dungeon/Evasive/Description.txt",                [PLAYER_1] = {{ red_icon = "hero_10_6_1", blue_icon = "hero_10_6_2" }, { red_icon = "hero_10_6_5", blue_icon = "hero_10_6_6" }}, [PLAYER_2] = {{ red_icon = "hero_10_6_3", blue_icon = "hero_10_6_4" }, { red_icon = "hero_10_6_7", blue_icon = "hero_10_6_8" }} },
	  { name = "Shadwyn",     txt = "dungeon/heroIlaiya.txt",     dsc = "/Text/Game/Heroes/Specializations/Dungeon/SpecShadwyn/Description.txt",            [PLAYER_1] = {{ red_icon = "hero_11_6_1", blue_icon = "hero_11_6_2" }, { red_icon = "hero_11_6_5", blue_icon = "hero_11_6_6" }}, [PLAYER_2] = {{ red_icon = "hero_11_6_3", blue_icon = "hero_11_6_4" }, { red_icon = "hero_11_6_7", blue_icon = "hero_11_6_8" }} },
--	  { name = "Thralsai",    txt = "dungeon/heroTralsai.txt",    dsc = "/Text/Game/Heroes/Specializations/Dungeon/SpecThralsai/Description.txt",           [PLAYER_1] = { red_icon = "hero_12_6_1", blue_icon = "hero_12_6_2" }, [PLAYER_2] = { red_icon = "hero_12_6_3", blue_icon = "hero_12_6_4" } }
  },
  [RACES.FORTRESS] = {
 	  { name = "Brand",       txt = "fortress/heroBrand.txt",      dsc = "/Text/Game/Heroes/Specializations/Fortress/Economist/Description.txt",    [PLAYER_1] = {{ red_icon = "hero_1_7_1", blue_icon = "hero_1_7_2" }, { red_icon = "hero_1_7_5", blue_icon = "hero_1_7_6" }}, [PLAYER_2] = {{ red_icon = "hero_1_7_3", blue_icon = "hero_1_7_4" }, { red_icon = "hero_1_7_7", blue_icon = "hero_1_7_8" }} },
	  { name = "Bersy",       txt = "fortress/heroIbba.txt",       dsc = "/Text/Game/Heroes/Specializations/Fortress/Rider/Description.txt",        [PLAYER_1] = {{ red_icon = "hero_2_7_1", blue_icon = "hero_2_7_2" }, { red_icon = "hero_2_7_5", blue_icon = "hero_2_7_6" }}, [PLAYER_2] = {{ red_icon = "hero_2_7_3", blue_icon = "hero_2_7_4" }, { red_icon = "hero_2_7_7", blue_icon = "hero_2_7_8" }} },
	  { name = "Egil",        txt = "fortress/heroErling.txt",     dsc = "/Text/Game/Heroes/Specializations/Fortress/Magister/Description.txt",     [PLAYER_1] = {{ red_icon = "hero_3_7_1", blue_icon = "hero_3_7_2" }, { red_icon = "hero_3_7_5", blue_icon = "hero_3_7_6" }}, [PLAYER_2] = {{ red_icon = "hero_3_7_3", blue_icon = "hero_3_7_4" }, { red_icon = "hero_3_7_7", blue_icon = "hero_3_7_8" }} },
	  { name = "Ottar",       txt = "fortress/heroHelmar.txt",     dsc = "/Text/Game/Heroes/Specializations/Fortress/Sacred_Hammer/Description.txt",[PLAYER_1] = {{ red_icon = "hero_4_7_1", blue_icon = "hero_4_7_2" }, { red_icon = "hero_4_7_5", blue_icon = "hero_4_7_6" }}, [PLAYER_2] = {{ red_icon = "hero_4_7_3", blue_icon = "hero_4_7_4" }, { red_icon = "hero_4_7_7", blue_icon = "hero_4_7_8" }} },
	  { name = "Una",         txt = "fortress/heroInga.txt",       dsc = "/Text/Game/Heroes/Specializations/Fortress/Researcher/Description.txt",   [PLAYER_1] = {{ red_icon = "hero_5_7_1", blue_icon = "hero_5_7_2" }, { red_icon = "hero_5_7_5", blue_icon = "hero_5_7_6" }}, [PLAYER_2] = {{ red_icon = "hero_5_7_3", blue_icon = "hero_5_7_4" }, { red_icon = "hero_5_7_7", blue_icon = "hero_5_7_8" }} },
	  { name = "Ingvar",      txt = "fortress/heroIngvar.txt",     dsc = "/Text/Game/Heroes/Specializations/Fortress/Defender/Description.txt",     [PLAYER_1] = {{ red_icon = "hero_6_7_1", blue_icon = "hero_6_7_2" }, { red_icon = "hero_6_7_5", blue_icon = "hero_6_7_6" }}, [PLAYER_2] = {{ red_icon = "hero_6_7_3", blue_icon = "hero_6_7_4" }, { red_icon = "hero_6_7_7", blue_icon = "hero_6_7_8" }} },
	  { name = "Vegeyr",      txt = "fortress/heroSveya.txt",      dsc = "/Text/Game/Heroes/Specializations/Fortress/Stormcaller/Description.txt",  [PLAYER_1] = {{ red_icon = "hero_7_7_1", blue_icon = "hero_7_7_2" }, { red_icon = "hero_7_7_5", blue_icon = "hero_7_7_6" }}, [PLAYER_2] = {{ red_icon = "hero_7_7_3", blue_icon = "hero_7_7_4" }, { red_icon = "hero_7_7_7", blue_icon = "hero_7_7_8" }} },
	  { name = "Skeggy",      txt = "fortress/heroKarli.txt",      dsc = "/Text/Game/Heroes/Specializations/Fortress/Axe_Master/Description.txt",   [PLAYER_1] = {{ red_icon = "hero_8_7_1", blue_icon = "hero_8_7_2" }, { red_icon = "hero_8_7_5", blue_icon = "hero_8_7_6" }}, [PLAYER_2] = {{ red_icon = "hero_8_7_3", blue_icon = "hero_8_7_4" }, { red_icon = "hero_8_7_7", blue_icon = "hero_8_7_8" }} },
--	  { name = "KingTolghar", txt = "fortress/heroTolgar.txt",     dsc = "/Text/Game/Heroes/Specializations/Fortress/Mountain_King/Description.txt",[PLAYER_1] = { red_icon = "hero_9_7_1", blue_icon = "hero_9_7_2" }, [PLAYER_2] = { red_icon = "hero_9_7_3", blue_icon = "hero_9_7_4" } },
	  { name = "Wulfstan",    txt = "fortress/heroVulfsten.txt",   dsc = "/Text/Game/Heroes/Specializations/Fortress/SpecWulfstan/Description.txt", [PLAYER_1] = {{ red_icon = "hero_10_7_1", blue_icon = "hero_10_7_2" }, { red_icon = "hero_10_7_5", blue_icon = "hero_10_7_6" }}, [PLAYER_2] = {{ red_icon = "hero_10_7_3", blue_icon = "hero_10_7_4" }, { red_icon = "hero_10_7_7", blue_icon = "hero_10_7_8" }} },
	  { name = "Rolf",        txt = "fortress/heroRolf.txt",       dsc = "/Text/Game/Heroes/Specializations/Fortress/SpecRolf/Description.txt",     [PLAYER_1] = {{ red_icon = "hero_11_7_1", blue_icon = "hero_11_7_2" }, { red_icon = "hero_11_7_5", blue_icon = "hero_11_7_6" }}, [PLAYER_2] = {{ red_icon = "hero_11_7_3", blue_icon = "hero_11_7_4" }, { red_icon = "hero_11_7_7", blue_icon = "hero_11_7_8" }} }
  },
  [RACES.STRONGHOLD] = {
--	  { name = "Hero2",       txt = "stronghold/heroArgat.txt",      dsc = "/Text/Game/Heroes/Specializations/Stronghold/SpecArgat/Description.txt",                  [PLAYER_1] = { red_icon = "hero_1_8_1", blue_icon = "hero_1_8_2" }, [PLAYER_2] = { red_icon = "hero_1_8_3", blue_icon = "hero_1_8_4" } },
	  { name = "Hero3",       txt = "stronghold/heroGaruna.txt",     dsc = "/Text/Game/Heroes/Specializations/Stronghold/Blooddrinker/Description.txt",               [PLAYER_1] = {{ red_icon = "hero_2_8_1", blue_icon = "hero_2_8_2" }, { red_icon = "hero_2_8_5", blue_icon = "hero_2_8_6" }}, [PLAYER_2] = {{ red_icon = "hero_2_8_3", blue_icon = "hero_2_8_4" }, { red_icon = "hero_2_8_7", blue_icon = "hero_2_8_8" }} },
	  { name = "Hero6",       txt = "stronghold/heroShakKarukat.txt",dsc = "/Text/Game/Heroes/Specializations/Stronghold/SpecShak/Description.txt",                   [PLAYER_1] = {{ red_icon = "hero_3_8_1", blue_icon = "hero_3_8_2" }, { red_icon = "hero_3_8_5", blue_icon = "hero_3_8_6" }}, [PLAYER_2] = {{ red_icon = "hero_3_8_3", blue_icon = "hero_3_8_4" }, { red_icon = "hero_3_8_7", blue_icon = "hero_3_8_8" }} },
	  { name = "Hero8",       txt = "stronghold/heroTilsek.txt",     dsc = "/Text/Game/Heroes/Specializations/Stronghold/GrimFighter/Description.txt",                [PLAYER_1] = {{ red_icon = "hero_4_8_1", blue_icon = "hero_4_8_2" }, { red_icon = "hero_4_8_5", blue_icon = "hero_4_8_6" }}, [PLAYER_2] = {{ red_icon = "hero_4_8_3", blue_icon = "hero_4_8_4" }, { red_icon = "hero_4_8_7", blue_icon = "hero_4_8_8" }} },
	  { name = "Hero7",       txt = "stronghold/heroHaggesh.txt",    dsc = "/Text/Game/Heroes/Specializations/Stronghold/CentaurMistress/Description.txt",            [PLAYER_1] = {{ red_icon = "hero_5_8_1", blue_icon = "hero_5_8_2" }, { red_icon = "hero_5_8_5", blue_icon = "hero_5_8_6" }}, [PLAYER_2] = {{ red_icon = "hero_5_8_3", blue_icon = "hero_5_8_4" }, { red_icon = "hero_5_8_7", blue_icon = "hero_5_8_8" }} },
 	  { name = "Hero1",       txt = "stronghold/heroKrag.txt",       dsc = "/Text/Game/Heroes/Specializations/Stronghold/Offender/Description.txt",                   [PLAYER_1] = {{ red_icon = "hero_6_8_1", blue_icon = "hero_6_8_2" }, { red_icon = "hero_6_8_5", blue_icon = "hero_6_8_6" }}, [PLAYER_2] = {{ red_icon = "hero_6_8_3", blue_icon = "hero_6_8_4" }, { red_icon = "hero_6_8_7", blue_icon = "hero_6_8_8" }} },
 	  { name = "Hero9",       txt = "stronghold/heroKigan.txt",      dsc = "/Text/Game/Heroes/Specializations/Stronghold/GoblinKing/Description.txt",                 [PLAYER_1] = {{ red_icon = "hero_7_8_1", blue_icon = "hero_7_8_2" }, { red_icon = "hero_7_8_5", blue_icon = "hero_7_8_6" }}, [PLAYER_2] = {{ red_icon = "hero_7_8_3", blue_icon = "hero_7_8_4" }, { red_icon = "hero_7_8_7", blue_icon = "hero_7_8_8" }} },
	  { name = "Hero4",       txt = "stronghold/heroGoshak.txt",     dsc = "/Text/Game/Heroes/Specializations/Stronghold/OrcElder/Description.txt",                   [PLAYER_1] = {{ red_icon = "hero_8_8_1", blue_icon = "hero_8_8_2" }, { red_icon = "hero_8_8_5", blue_icon = "hero_8_8_6" }}, [PLAYER_2] = {{ red_icon = "hero_8_8_3", blue_icon = "hero_8_8_4" }, { red_icon = "hero_8_8_7", blue_icon = "hero_8_8_8" }} },
	  { name = "Kujin",       txt = "stronghold/heroKudgin.txt",     dsc = "/Text/Game/Heroes/Specializations/Stronghold/SpecKujin/Description.txt",                  [PLAYER_1] = {{ red_icon = "hero_9_8_1", blue_icon = "hero_9_8_2" }, { red_icon = "hero_9_8_5", blue_icon = "hero_9_8_6" }}, [PLAYER_2] = {{ red_icon = "hero_9_8_3", blue_icon = "hero_9_8_4" }, { red_icon = "hero_9_8_7", blue_icon = "hero_9_8_8" }} },
	  { name = "Gottai",      txt = "stronghold/heroGotai.txt",      dsc = "/Text/Game/Heroes/Specializations/Stronghold/WarLeader/Description.txt",                  [PLAYER_1] = {{ red_icon = "hero_10_8_1", blue_icon = "hero_10_8_2" }, { red_icon = "hero_10_8_5", blue_icon = "hero_10_8_6" }}, [PLAYER_2] = {{ red_icon = "hero_10_8_3", blue_icon = "hero_10_8_4" }, { red_icon = "hero_10_8_7", blue_icon = "hero_10_8_8" }} },
	  { name = "Quroq",       txt = "stronghold/heroKurak.txt",      dsc = "/Text/Game/Heroes/Specializations/Stronghold/SpecQuroq/Description.txt",                  [PLAYER_1] = {{ red_icon = "hero_11_8_1", blue_icon = "hero_11_8_2" }, { red_icon = "hero_11_8_5", blue_icon = "hero_11_8_6" }}, [PLAYER_2] = {{ red_icon = "hero_11_8_3", blue_icon = "hero_11_8_4" }, { red_icon = "hero_11_8_7", blue_icon = "hero_11_8_8" }} }
  }
};

-- Биара (герой красного)
Biara = GetPlayerHeroes(PLAYER_1)[0]
-- Джованни (негой синего)
Djovanni = GetPlayerHeroes(PLAYER_2)[0]

-- Итоговый список расы и героев для игры
-- Служит для передачи значения для начала прокачки
RESULT_HERO_LIST = {
  [PLAYER_1] = { raceId = nil, heroes = {} },
  [PLAYER_2] = { raceId = nil, heroes = {} },
};

-- Таблица ИД всех игроков
PLAYER_ID_TABLE = { PLAYER_1, PLAYER_2 };

-- Список начальных навыков и/или школ для каждого героя
INITIAL_HERO_SKILLS = {
  Orrin = { SKILL_OFFENCE, PERK_ARCHERY },
  Sarge = { SKILL_OFFENCE, PERK_HOLY_CHARGE },
  Mardigo = { SKILL_DEFENCE, PERK_TOUGHNESS },
  Brem = { SKILL_TRAINING, SKILL_TRAINING },
  Maeve = { SKILL_LIGHT_MAGIC, PERK_MASTER_OF_WRATH },
  Ving = { SKILL_LUCK, PERK_RESISTANCE },
  Nathaniel = { SKILL_LEADERSHIP, PERK_RECRUITMENT },
  Christian = { SKILL_WAR_MACHINES, PERK_BALLISTA },
  Godric = { SKILL_LIGHT_MAGIC, PERK_PRAYER },
  RedHeavenHero03 = { SKILL_SORCERY, SKILL_DARK_MAGIC },
  Isabell_A1 = { SKILL_LIGHT_MAGIC, SKILL_LIGHT_MAGIC },
  Duncan = { SKILL_OFFENCE, PERK_TACTICS },
  Nicolai = { SKILL_TRAINING, SKILL_TRAINING },
  Grok = { SKILL_LOGISTICS, PERK_PATHFINDING },
  Oddrema = { SKILL_SORCERY, PERK_WISDOM },
  Marder = { SKILL_DEFENCE, PERK_PROTECTION },
  Jazaz = { SKILL_OFFENCE, PERK_TACTICS },
  Efion = { SKILL_DARK_MAGIC, SKILL_DARK_MAGIC },
  Deleb = { SKILL_WAR_MACHINES, PERK_BALLISTA },
  Calid = { SKILL_DESTRUCTIVE_MAGIC, PERK_DEMONIC_FIRE },
  Nymus = { SKILL_LUCK, PERK_RESISTANCE },
  Orlando = { SKILL_LEADERSHIP, PERK_DEMONIC_STRIKE },
  Agrael = { SKILL_OFFENCE, PERK_FRENZY },
  ["Kha-Beleth"] = { SKILL_DARK_MAGIC, PERK_DEMONIC_FIRE },
  Nemor = { SKILL_OFFENCE, PERK_FRENZY },
  Tamika = { SKILL_OFFENCE, PERK_FRENZY },
  Muscip = { SKILL_SUMMONING_MAGIC, SKILL_DARK_MAGIC },
  Aberrar = { SKILL_LEARNING, PERK_INTELLIGENCE },
  Straker = { SKILL_DEFENCE, PERK_TOUGHNESS },
  Effig = { SKILL_DARK_MAGIC, PERK_MASTER_OF_CURSES },
  Pelt = { SKILL_SUMMONING_MAGIC, PERK_MASTER_OF_ANIMATION },
  Gles = { SKILL_WAR_MACHINES, PERK_FIRST_AID },
  Arantir = { SKILL_SUMMONING_MAGIC, NECROMANCER_FEAT_SPIRIT_LINK },
  OrnellaNecro = { SKILL_LEADERSHIP, PERK_NO_REST_FOR_THE_WICKED },
  Berein = { SKILL_NECROMANCY, SKILL_NECROMANCY },
  Nikolas = { SKILL_LEARNING, SKILL_LEARNING },
  Metlirn = { SKILL_AVENGER, SKILL_AVENGER },
  Gillion = { SKILL_DEFENCE, PERK_TOUGHNESS },
  Nadaur = { SKILL_LEADERSHIP, PERK_RECRUITMENT },
  Diraya = { SKILL_SUMMONING_MAGIC, PERK_MASTER_OF_CREATURES },
  Ossir = { SKILL_LUCK, PERK_RESISTANCE },
  Itil = { SKILL_LIGHT_MAGIC, PERK_MASTER_OF_BLESSING },
  Elleshar = { SKILL_LEARNING, PERK_INTELLIGENCE },
  Linaas = { SKILL_OFFENCE, PERK_TACTICS },
  Heam = { SKILL_OFFENCE, PERK_ARCHERY },
  Ildar = { SKILL_LIGHT_MAGIC, SKILL_LIGHT_MAGIC },
  GhostFSLord = { SKILL_LEARNING, SKILL_SUMMONING_MAGIC },
  Faiz = { SKILL_DARK_MAGIC, PERK_MASTER_OF_SICKNESS },
  Havez = { SKILL_WAR_MACHINES, PERK_MELT_ARTIFACT },
  Nur = { SKILL_DESTRUCTIVE_MAGIC, PERK_MASTER_OF_FIRE },
  Astral = { SKILL_SORCERY, PERK_MAGIC_BOND },
  Sufi = { SKILL_SORCERY, PERK_ARCANE_TRAINING },
  Razzak = { SKILL_LEARNING, PERK_INTELLIGENCE },
  Tan = { SKILL_LUCK, PERK_MAGIC_MIRROR },
  Isher = { SKILL_DEFENCE, PERK_TOUGHNESS },
  Zehir = { SKILL_SUMMONING_MAGIC, PERK_MASTER_OF_CREATURES },
  Maahir = { SKILL_ARTIFICIER, SKILL_ARTIFICIER },
  Cyrus = { SKILL_LIGHT_MAGIC, SKILL_LIGHT_MAGIC },
  Eruina = { SKILL_OFFENCE, SKILL_DESTRUCTIVE_MAGIC },
  Inagost = { SKILL_DESTRUCTIVE_MAGIC, PERK_EMPOWERED_SPELLS },
  Urunir = { SKILL_LEARNING, PERK_INTELLIGENCE },
  Almegir = { SKILL_SUMMONING_MAGIC, PERK_DARK_RITUAL },
  Menel = { SKILL_LEADERSHIP, PERK_ESTATES },
  Dalom = { SKILL_DARK_MAGIC, PERK_MASTER_OF_SICKNESS },
  Ferigl = { SKILL_OFFENCE, PERK_FRENZY },
  Ohtarig = { SKILL_LUCK, PERK_LUCKY_STRIKE },
  Raelag_A1 = { SKILL_LOGISTICS, SKILL_INVOCATION },
  Kelodin = { SKILL_DEFENCE, PERK_EVASION },
  Shadwyn = { SKILL_INVOCATION, NECROMANCER_FEAT_ABSOLUTE_FEAR },
  Thralsai = { SKILL_LEARNING,  SKILL_LEARNING },
  Brand = { HERO_SKILL_RUNELORE, HERO_SKILL_FINE_RUNE },
  Bersy = { SKILL_OFFENCE, PERK_TACTICS },
  Egil = { SKILL_SORCERY, SKILL_SORCERY },
  Ottar = { SKILL_LIGHT_MAGIC, SKILL_LIGHT_MAGIC },
  Una = { SKILL_LEARNING, PERK_SCHOLAR },
  Ingvar = { SKILL_DEFENCE, PERK_TOUGHNESS },
  Vegeyr = { SKILL_DESTRUCTIVE_MAGIC, PERK_MASTER_OF_LIGHTNINGS },
  Skeggy = { SKILL_LUCK, PERK_LUCKY_STRIKE },
  KingTolghar = { HERO_SKILL_RUNELORE, HERO_SKILL_RUNELORE },
  Wulfstan = { SKILL_LOGISTICS, PERK_PATHFINDING },
  Rolf = { SKILL_LEADERSHIP, PERK_DIPLOMACY },
  Hero2 = { SKILL_WAR_MACHINES, PERK_FIRST_AID },
  Hero3 = { SKILL_OFFENCE, PERK_FRENZY },
  Hero6 = { SKILL_DEFENCE, PERK_TOUGHNESS },
  Hero8 = { SKILL_WAR_MACHINES, HERO_SKILL_MIGHT_OVER_MAGIC },
  Hero7 = { SKILL_OFFENCE, PERK_ARCHERY },
  Hero1 = { SKILL_OFFENCE, HERO_SKILL_POWERFULL_BLOW },
  Hero9 = { SKILL_LEADERSHIP, PERK_RECRUITMENT },
  Hero4 = { HERO_SKILL_DEMONIC_RAGE, HERO_SKILL_POWERFULL_BLOW },
  Kujin = { HERO_SKILL_BARBARIAN_LEARNING, HERO_SKILL_MEMORY_OF_OUR_BLOOD },
  Gottai = { HERO_SKILL_DEMONIC_RAGE, HERO_SKILL_VOICE },
  Quroq = { HERO_SKILL_VOICE, HERO_SKILL_VOICE_OF_RAGE },
};

-- Соотношение словарного названия героя с названия героев, выданных игрокам
MAPPING_HERO_NAME_TO_PLAYERS_HERO_NAME = {
    { dictName = "Orrin", reservedNames = { "Orrin", "Orrin2" } },
    { dictName = "Sarge", reservedNames = { "Sarge", "Sarge2" } },
    { dictName = "Mardigo", reservedNames = { "Mardigo", "Mardigo2" } },
    { dictName = "Brem", reservedNames = { "Brem", "Brem2" } },
    { dictName = "Maeve", reservedNames = { "Maeve", "Maeve2" } },
    { dictName = "Ving", reservedNames = { "Ving", "Ving2" } },
    { dictName = "Nathaniel", reservedNames = { "Nathaniel", "Nathaniel2" } },
    { dictName = "Christian", reservedNames = { "Christian", "Christian2" } },
    { dictName = "Godric", reservedNames = { "Godric", "Godric2" } },
    { dictName = "RedHeavenHero03", reservedNames = { "RedHeavenHero03", "RedHeavenHero032" } },
    { dictName = "Isabell_A1", reservedNames = { "Isabell_A1", "Isabell_A12" } },
    { dictName = "Duncan", reservedNames = { "Duncan", "Duncan2" } },
    { dictName = "Nicolai", reservedNames = { "Nicolai", "Nicolai2" } },
    { dictName = "Grok", reservedNames = { "Grok", "Grok2" } },
    { dictName = "Oddrema", reservedNames = {"Oddrema", "Oddrema2" } },
    { dictName = "Marder", reservedNames = { "Marder", "Marder2" } },
    { dictName = "Jazaz", reservedNames = { "Jazaz", "Jazaz2" } },
    { dictName = "Efion", reservedNames = { "Efion", "Efion2" } },
    { dictName = "Deleb", reservedNames = { "Deleb", "Deleb2" } },
    { dictName = "Calid", reservedNames = { "Calid", "Calid2" } },
    { dictName = "Nymus", reservedNames = { "Nymus", "Nymus2" } },
    { dictName = "Orlando", reservedNames = { "Orlando", "Orlando2" } },
    { dictName = "Agrael", reservedNames = { "Agrael", "Agrael2" } },
    { dictName = "Kha-Beleth", reservedNames = { "Kha-Beleth", "Kha-Beleth2" } },
    { dictName = "Nemor", reservedNames = { "Nemor", "Nemor2" } },
    { dictName = "Tamika", reservedNames = { "Tamika", "Tamika2" } },
    { dictName = "Muscip", reservedNames = { "Muscip", "Muscip2" } },
    { dictName = "Aberrar", reservedNames = { "Aberrar", "Aberrar2" } },
    { dictName = "Straker", reservedNames = { "Straker", "Straker2" } },
    { dictName = "Effig", reservedNames = { "Effig", "Effig2" } },
    { dictName = "Pelt", reservedNames = { "Pelt", "Pelt2" } },
    { dictName = "Gles", reservedNames = { "Gles", "Gles2" } },
    { dictName = "Arantir", reservedNames = { "Arantir", "Arantir2" } },
    { dictName = "OrnellaNecro", reservedNames = { "OrnellaNecro", "OrnellaNecro2" } },
    { dictName = "Berein", reservedNames = { "Berein", "Berein2" } },
    { dictName = "Nikolas", reservedNames = { "Nikolas", "Nikolas2" } },
    { dictName = "Metlirn", reservedNames = { "Metlirn", "Metlirn2" } },
    { dictName = "Gillion", reservedNames = { "Gillion", "Gillion2" } },
    { dictName = "Nadaur", reservedNames = { "Nadaur", "Nadaur2" } },
    { dictName = "Diraya", reservedNames = { "Diraya", "Diraya2" } },
    { dictName = "Ossir", reservedNames = { "Ossir", "Ossir2" } },
    { dictName = "Itil", reservedNames = { "Itil", "Itil2" } },
    { dictName = "Elleshar", reservedNames = { "Elleshar", "Elleshar2" } },
    { dictName = "Linaas", reservedNames = { "Linaas", "Linaas2" } },
    { dictName = "Heam", reservedNames = { "Heam", "Heam2" } },
    { dictName = "Ildar", reservedNames = { "Ildar", "Ildar2" } },
    { dictName = "GhostFSLord", reservedNames = { "GhostFSLord", "GhostFSLord2" } },
    { dictName = "Faiz", reservedNames = { "Faiz", "Faiz2" } },
    { dictName = "Havez", reservedNames = { "Havez", "Havez2" } },
    { dictName = "Nur", reservedNames = { "Nur", "Nur2" } },
    { dictName = "Astral", reservedNames = { "Astral", "Astral2" } },
    { dictName = "Sufi", reservedNames = { "Sufi", "Sufi2" } },
    { dictName = "Razzak", reservedNames = { "Razzak", "Razzak2" } },
    { dictName = "Tan", reservedNames = { "Tan", "Tan2" } },
    { dictName = "Isher", reservedNames = { "Isher", "Isher2" } },
    { dictName = "Zehir", reservedNames = { "Zehir", "Zehir2" } },
    { dictName = "Maahir", reservedNames = { "Maahir", "Maahir2" } },
    { dictName = "Cyrus", reservedNames = { "Cyrus", "Cyrus2" } },
    { dictName = "Eruina", reservedNames = { "Eruina", "Eruina2" } },
    { dictName = "Inagost", reservedNames = { "Inagost", "Inagost2" } },
    { dictName = "Urunir", reservedNames = { "Urunir", "Urunir2" } },
    { dictName = "Almegir", reservedNames = { "Almegir", "Almegir2" } },
    { dictName = "Menel", reservedNames = { "Menel", "Menel2" } },
    { dictName = "Dalom", reservedNames = { "Dalom", "Dalom2" } },
    { dictName = "Ferigl", reservedNames = { "Ferigl", "Ferigl2" } },
    { dictName = "Ohtarig", reservedNames = { "Ohtarig", "Ohtarig2" } },
    { dictName = "Raelag_A1", reservedNames = { "Raelag_A1", "Raelag_A12" } },
    { dictName = "Kelodin", reservedNames = { "Kelodin", "Kelodin2" } },
    { dictName = "Shadwyn", reservedNames = { "Shadwyn", "Shadwyn2" } },
    { dictName = "Thralsai", reservedNames = { "Thralsai", "Thralsai2" } },
    { dictName = "Brand", reservedNames = { "Brand", "Brand2" } },
    { dictName = "Bersy", reservedNames = { "Bersy", "Bersy2" } },
    { dictName = "Egil", reservedNames = { "Egil", "Egil2" } },
    { dictName = "Ottar", reservedNames = { "Ottar", "Ottar2" } },
    { dictName = "Una", reservedNames = { "Una", "Una2" } },
    { dictName = "Ingvar", reservedNames = { "Ingvar", "Ingvar2" } },
    { dictName = "Vegeyr", reservedNames = { "Vegeyr", "Vegeyr2" } },
    { dictName = "Skeggy", reservedNames = { "Skeggy", "Skeggy2" } },
    { dictName = "KingTolghar", reservedNames = { "KingTolghar", "KingTolghar2" } },
    { dictName = "Wulfstan", reservedNames = { "Wulfstan", "Wulfstan2" } },
    { dictName = "Rolf", reservedNames = { "Rolf", "Rolf2" } },
    { dictName = "Hero2", reservedNames = { "Hero2", "Hero22" } },
    { dictName = "Hero3", reservedNames = { "Hero3", "Hero32" } },
    { dictName = "Hero6", reservedNames = { "Hero6", "Hero62" } },
    { dictName = "Hero8", reservedNames = { "Hero8", "Hero82" } },
    { dictName = "Hero7", reservedNames = { "Hero7", "Hero72" } },
    { dictName = "Hero1", reservedNames = { "Hero1", "Hero12" } },
    { dictName = "Hero9", reservedNames = { "Hero9", "Hero92" } },
    { dictName = "Hero4", reservedNames = { "Hero4", "Hero42" } },
    { dictName = "Kujin", reservedNames = { "Kujin", "Kujin2" } },
    { dictName = "Gottai", reservedNames = { "Gottai", "Gottai2" } },
    { dictName = "Quroq", reservedNames = { "Quroq", "Quroq2" } },
};
