-- Файл предназначен для хранение общеигровых фиксированных данных: например тип черка

-- ИД выбранной сложности игры
local DIFFICULTY = GetDifficulty();

-- NOTE: Почему то результат вычислений это 0 или 1, но при этом все равно корректно работает в условия
-- Маппинг сложности игры на черк
GAME_MODE = {
  -- Простой выбор (REKRUT)
  SIMPLE_CHOOSE = DIFFICULTY == DIFFICULTY_EASY,
  -- Черк матчапов (VOIN)
  MATCHUPS = DIFFICULTY == DIFFICULTY_NORMAL,
  -- Получерк (VETERAN)
  HALF = DIFFICULTY == DIFFICULTY_HARD,
  -- Микс черк (GEROI)
  MIX = DIFFICULTY == DIFFICULTY_HEROIC,
}

-- Кастомное перечисление рас, за неимением такого по умолчанию
RACES = {
  -- Орден Порядка
  HAVEN = 0,
  -- Инферно
  INFERNO = 1,
  -- Некрополис
  NECROPOLIS = 2,
  -- Лесной Союз
  SYLVAN = 3,
  -- Акадения Волшебства
  ACADEMY = 4,
  -- Лига Теней
  DUNGEON = 5,
  -- Дварфы
  FORTRESS = 6,
  -- Орда
  STRONGHOLD = 7,
};

------------------ ГЕРОИ, ИСПОЛЬЗУЮЩИЕСЯ В КАРТЕ ------------------------
HEROES_BY_RACE = {
  [RACES.HAVEN] = {
	  { name = "Orrin",           txt = "haven/heroDugal.txt",    dsc = "/Text/Game/Heroes/Specializations/Haven/Archer_Commander/Description.txt",   [PLAYER_1] = { red_icon = "hero_1_1_1", blue_icon = "hero_1_1_2" }, [PLAYER_2] = { red_icon = "hero_1_1_3", blue_icon = "hero_1_1_4" } },
	  { name = "Sarge",           txt = "haven/heroAksel.txt",    dsc = "/Text/Game/Heroes/Specializations/Haven/Jouster/Description.txt",            [PLAYER_1] = { red_icon = "hero_2_1_1", blue_icon = "hero_2_1_2" }, [PLAYER_2] = { red_icon = "hero_2_1_3", blue_icon = "hero_2_1_4" } },
	  { name = "Mardigo",         txt = "haven/heroLaslo.txt",    dsc = "/Text/Game/Heroes/Specializations/Haven/Infantry_Commander/Description.txt", [PLAYER_1] = { red_icon = "hero_3_1_1", blue_icon = "hero_3_1_2" }, [PLAYER_2] = { red_icon = "hero_3_1_3", blue_icon = "hero_3_1_4" } },
	  { name = "Brem",            txt = "haven/heroRutger.txt",   dsc = "/Text/Game/Heroes/Specializations/Haven/Wanderer/Description.txt",           [PLAYER_1] = { red_icon = "hero_4_1_1", blue_icon = "hero_4_1_2" }, [PLAYER_2] = { red_icon = "hero_4_1_3", blue_icon = "hero_4_1_4" } },
	  { name = "Maeve",           txt = "haven/heroMiv.txt",      dsc = "/Text/Game/Heroes/Specializations/Haven/Expediter/Description.txt",          [PLAYER_1] = { red_icon = "hero_5_1_1", blue_icon = "hero_5_1_2" }, [PLAYER_2] = { red_icon = "hero_5_1_3", blue_icon = "hero_5_1_4" } },
	  { name = "Ving",            txt = "haven/heroAiris.txt",    dsc = "/Text/Game/Heroes/Specializations/Haven/Griffon_Commander/Description.txt",  [PLAYER_1] = { red_icon = "hero_6_1_1", blue_icon = "hero_6_1_2" }, [PLAYER_2] = { red_icon = "hero_6_1_3", blue_icon = "hero_6_1_4" } },
	  { name = "Nathaniel",       txt = "haven/heroEllaina.txt",  dsc = "/Text/Game/Heroes/Specializations/Haven/Squire/Description.txt",             [PLAYER_1] = { red_icon = "hero_7_1_1", blue_icon = "hero_7_1_2" }, [PLAYER_2] = { red_icon = "hero_7_1_3", blue_icon = "hero_7_1_4" } },
	  { name = "Christian",       txt = "haven/heroVittorio.txt", dsc = "/Text/Game/Heroes/Specializations/Haven/Artilleryman/Description.txt",       [PLAYER_1] = { red_icon = "hero_8_1_1", blue_icon = "hero_8_1_2" }, [PLAYER_2] = { red_icon = "hero_8_1_3", blue_icon = "hero_8_1_4" } },
	  { name = "Godric",          txt = "haven/heroGodric.txt",   dsc = "/Text/Game/Heroes/Specializations/Haven/White_Knight/Description.txt",       [PLAYER_1] = { red_icon = "hero_9_1_1", blue_icon = "hero_9_1_2" }, [PLAYER_2] = { red_icon = "hero_9_1_3", blue_icon = "hero_9_1_4" } },
    { name = "RedHeavenHero03", txt = "haven/heroValeria.txt",  dsc = "/Text/Game/Heroes/Specializations/Haven/SpecValeria/Description.txt",        [PLAYER_1] = { red_icon = "hero_13_1_1", blue_icon = "hero_13_1_2" }, [PLAYER_2] = { red_icon = "hero_13_1_3", blue_icon = "hero_13_1_4" } },
--	  { name = "Isabell_A1",      txt = "haven/heroIsabel.txt",   p1 = "hero_11_1_1", p2 = "hero_11_1_2", p3 = "hero_11_1_3", p4 = "hero_11_1_4", dsc = "/Text/Game/Heroes/Specializations/Haven/Archer_Commander/Description.txt"},
--	  { name = "Duncan",          txt = "haven/heroDuncan.txt",   p1 = "hero_12_1_1", p2 = "hero_12_1_2", p3 = "hero_12_1_3", p4 = "hero_12_1_4", dsc = "/Text/Game/Heroes/Specializations/Haven/Archer_Commander/Description.txt"},
--    { name = "Nicolai",         txt = "haven/heroNicolai.txt",  p1 = "hero_10_1_1", p2 = "hero_10_1_2", p3 = "hero_10_1_3", p4 = "hero_10_1_4", dsc = "/Text/Game/Heroes/Specializations/Haven/Archer_Commander/Description.txt"}
  },
  [RACES.INFERNO] = {
	  { ["name"] = "Grok",        ["name2"] = "Grok2",        ["blocked"] = 0, ["taverna"] = 1, ["skill1"] =   1, ["skill2"] =  19, ["looser"] = 1, ["ver"] = 100, ["txt"] = "inferno/heroGrok.txt",       ["p1"] = "hero_1_2_1", ["p2"] = "hero_1_2_2", ["p3"] = "hero_1_2_3", ["p4"] = "hero_1_2_4", ["p5"] = "hero_1_2_5", ["p6"] = "hero_1_2_6", ["p7"] = "hero_1_2_7", ["p8"] = "hero_1_2_8", ["block_temply"] = 0, ["dsc"] = "/Text/Game/Heroes/Specializations/Inferno/Beater/Description.txt" },
	  { ["name"] = "Oddrema",     ["name2"] = "Oddrema2",     ["blocked"] = 0, ["taverna"] = 1, ["skill1"] =   8, ["skill2"] =  41, ["looser"] = 0, ["ver"] = 100, ["txt"] = "inferno/heroDgezebet.txt",   ["p1"] = "hero_2_2_1", ["p2"] = "hero_2_2_2", ["p3"] = "hero_2_2_3", ["p4"] = "hero_2_2_4", ["p5"] = "hero_2_2_5", ["p6"] = "hero_2_2_6", ["p7"] = "hero_2_2_7", ["p8"] = "hero_2_2_8", ["block_temply"] = 0, ["dsc"] = "/Text/Game/Heroes/Specializations/Inferno/Temptress/Description.txt" },
    { ["name"] = "Marder",      ["name2"] = "Marder2",      ["blocked"] = 0, ["taverna"] = 1, ["skill1"] =   7, ["skill2"] =  37, ["looser"] = 0, ["ver"] = 100, ["txt"] = "inferno/heroMarbas.txt",     ["p1"] = "hero_3_2_1", ["p2"] = "hero_3_2_2", ["p3"] = "hero_3_2_3", ["p4"] = "hero_3_2_4", ["p5"] = "hero_3_2_5", ["p6"] = "hero_3_2_6", ["p7"] = "hero_3_2_7", ["p8"] = "hero_3_2_8", ["block_temply"] = 0, ["dsc"] = "/Text/Game/Heroes/Specializations/Inferno/Impregnable/Description.txt" },
	  { ["name"] = "Jazaz",       ["name2"] = "Jazaz2",       ["blocked"] = 0, ["taverna"] = 1, ["skill1"] =   6, ["skill2"] =  34, ["looser"] = 0, ["ver"] = 100, ["txt"] = "inferno/heroNibros.txt",     ["p1"] = "hero_4_2_1", ["p2"] = "hero_4_2_2", ["p3"] = "hero_4_2_3", ["p4"] = "hero_4_2_4", ["p5"] = "hero_4_2_5", ["p6"] = "hero_4_2_6", ["p7"] = "hero_4_2_7", ["p8"] = "hero_4_2_8", ["block_temply"] = 0, ["dsc"] = "/Text/Game/Heroes/Specializations/Inferno/Flagbearer_of_Darkness/Description.txt" },
	  { ["name"] = "Efion",       ["name2"] = "Efion2",       ["blocked"] = 0, ["taverna"] = 1, ["skill1"] =  10, ["skill2"] =  10, ["looser"] = 0, ["ver"] = 100, ["txt"] = "inferno/heroAlastor.txt",    ["p1"] = "hero_5_2_1", ["p2"] = "hero_5_2_2", ["p3"] = "hero_5_2_3", ["p4"] = "hero_5_2_4", ["p5"] = "hero_5_2_5", ["p6"] = "hero_5_2_6", ["p7"] = "hero_5_2_7", ["p8"] = "hero_5_2_8", ["block_temply"] = 0, ["dsc"] = "/Text/Game/Heroes/Specializations/Inferno/Hypnotist/Description.txt" },
	  { ["name"] = "Deleb",       ["name2"] = "Deleb2",       ["blocked"] = 0, ["taverna"] = 1, ["skill1"] =   2, ["skill2"] =  23, ["looser"] = 1, ["ver"] = 100, ["txt"] = "inferno/heroDeleb.txt",      ["p1"] = "hero_6_2_1", ["p2"] = "hero_6_2_2", ["p3"] = "hero_6_2_3", ["p4"] = "hero_6_2_4", ["p5"] = "hero_6_2_5", ["p6"] = "hero_6_2_6", ["p7"] = "hero_6_2_7", ["p8"] = "hero_6_2_8", ["block_temply"] = 0, ["dsc"] = "/Text/Game/Heroes/Specializations/Inferno/Bombardier/Description.txt" },
	  { ["name"] = "Calid",       ["name2"] = "Calid2",       ["blocked"] = 0, ["taverna"] = 1, ["skill1"] =   9, ["skill2"] =  59, ["looser"] = 0, ["ver"] = 100, ["txt"] = "inferno/heroGrol.txt",       ["p1"] = "hero_7_2_1", ["p2"] = "hero_7_2_2", ["p3"] = "hero_7_2_3", ["p4"] = "hero_7_2_4", ["p5"] = "hero_7_2_5", ["p6"] = "hero_7_2_6", ["p7"] = "hero_7_2_7", ["p8"] = "hero_7_2_8", ["block_temply"] = 0, ["dsc"] = "/Text/Game/Heroes/Specializations/Inferno/Breeder/Description.txt" },
	  { ["name"] = "Nymus",       ["name2"] = "Nymus2",       ["blocked"] = 0, ["taverna"] = 1, ["skill1"] =   5, ["skill2"] =  31, ["looser"] = 0, ["ver"] = 100, ["txt"] = "inferno/heroNimus.txt",      ["p1"] = "hero_8_2_1", ["p2"] = "hero_8_2_2", ["p3"] = "hero_8_2_3", ["p4"] = "hero_8_2_4", ["p5"] = "hero_8_2_5", ["p6"] = "hero_8_2_6", ["p7"] = "hero_8_2_7", ["p8"] = "hero_8_2_8", ["block_temply"] = 0, ["dsc"] = "/Text/Game/Heroes/Specializations/Inferno/Gate_Keeper/Description.txt" },
	  { ["name"] = "Orlando",     ["name2"] = "Orlando2",     ["blocked"] = 0, ["taverna"] = 1, ["skill1"] =   4, ["skill2"] =  60, ["looser"] = 0, ["ver"] = 100, ["txt"] = "inferno/heroOrlando.txt",    ["p1"] = "hero_9_2_1", ["p2"] = "hero_9_2_2", ["p3"] = "hero_9_2_3", ["p4"] = "hero_9_2_4", ["p5"] = "hero_9_2_5", ["p6"] = "hero_9_2_6", ["p7"] = "hero_9_2_7", ["p8"] = "hero_9_2_8", ["block_temply"] = 0, ["dsc"] = "/Text/Game/Heroes/Specializations/Inferno/SpecOrlando/Description.txt" },
	  { ["name"] = "Agrael",      ["name2"] = "Agrael2",      ["blocked"] = 0, ["taverna"] = 1, ["skill1"] =   6, ["skill2"] =  36, ["looser"] = 0, ["ver"] = 100, ["txt"] = "inferno/heroAgrail.txt",     ["p1"] = "hero_10_2_1",["p2"] = "hero_10_2_2",["p3"] = "hero_10_2_3",["p4"] = "hero_10_2_4",["p5"] = "hero_10_2_5",["p6"] = "hero_10_2_6",["p7"] = "hero_10_2_7",["p8"] = "hero_10_2_8",["block_temply"] = 0, ["dsc"] = "/Text/Game/Heroes/Specializations/Inferno/SpecAgrael/Description.txt" },
	  { ["name"] = "Kha-Beleth",  ["name2"] = "Kha-Beleth2",  ["blocked"] = 1, ["taverna"] = 1, ["skill1"] =  10, ["skill2"] =  59, ["looser"] = 0, ["ver"] = 100, ["txt"] = "inferno/heroVlastelin.txt",  ["p1"] = "hero_11_2_1",["p2"] = "hero_11_2_2",["p3"] = "hero_11_2_3",["p4"] = "hero_11_2_4",["p5"] = "hero_11_2_5",["p6"] = "hero_11_2_6",["p7"] = "hero_11_2_7",["p8"] = "hero_11_2_8",["block_temply"] = 0, ["dsc"] = "/Text/Game/Heroes/Specializations/Inferno/Beater/Description.txt" }
  },
  [RACES.NECROPOLIS] = {
	  { ["name"] = "Nemor",       ["name2"] = "Nemor2",       ["blocked"] = 0, ["taverna"] = 1, ["skill1"] =  10, ["skill2"] =  63, ["looser"] = 1, ["ver"] = 100, ["txt"] = "necropolis/heroDeidra.txt",     ["p1"] = "hero_1_3_1", ["p2"] = "hero_1_3_2", ["p3"] = "hero_1_3_3", ["p4"] = "hero_1_3_4", ["p5"] = "hero_1_3_5", ["p6"] = "hero_1_3_6", ["p7"] = "hero_1_3_7", ["p8"] = "hero_1_3_8", ["block_temply"] = 0, ["dsc"] = "/Text/Game/Heroes/Specializations/Necropolis/Dark_Emissary/Description.txt" },
	  { ["name"] = "Tamika",      ["name2"] = "Tamika2",      ["blocked"] = 0, ["taverna"] = 1, ["skill1"] =   8, ["skill2"] =  42, ["looser"] = 0, ["ver"] = 100, ["txt"] = "necropolis/heroLukrecia.txt",   ["p1"] = "hero_2_3_1", ["p2"] = "hero_2_3_2", ["p3"] = "hero_2_3_3", ["p4"] = "hero_2_3_4", ["p5"] = "hero_2_3_5", ["p6"] = "hero_2_3_6", ["p7"] = "hero_2_3_7", ["p8"] = "hero_2_3_8", ["block_temply"] = 0, ["dsc"] = "/Text/Game/Heroes/Specializations/Necropolis/Vamipre_Princess/Description.txt" },
	  { ["name"] = "Muscip",      ["name2"] = "Muscip2",      ["blocked"] = 0, ["taverna"] = 1, ["skill1"] =  12, ["skill2"] =  10, ["looser"] = 0, ["ver"] = 100, ["txt"] = "necropolis/heroNaadir.txt",     ["p1"] = "hero_3_3_1", ["p2"] = "hero_3_3_2", ["p3"] = "hero_3_3_3", ["p4"] = "hero_3_3_4", ["p5"] = "hero_3_3_5", ["p6"] = "hero_3_3_6", ["p7"] = "hero_3_3_7", ["p8"] = "hero_3_3_8", ["block_temply"] = 0, ["dsc"] = "/Text/Game/Heroes/Specializations/Necropolis/Soulhunter/Description.txt" },
	  { ["name"] = "Aberrar",     ["name2"] = "Aberrar2",     ["blocked"] = 0, ["taverna"] = 1, ["skill1"] =   3, ["skill2"] =  25, ["looser"] = 0, ["ver"] = 100, ["txt"] = "necropolis/heroZoltan.txt",     ["p1"] = "hero_4_3_1", ["p2"] = "hero_4_3_2", ["p3"] = "hero_4_3_3", ["p4"] = "hero_4_3_4", ["p5"] = "hero_4_3_5", ["p6"] = "hero_4_3_6", ["p7"] = "hero_4_3_7", ["p8"] = "hero_4_3_8", ["block_temply"] = 0, ["dsc"] = "/Text/Game/Heroes/Specializations/Necropolis/Mind_Cleaner/Description.txt" },
	  { ["name"] = "Straker",     ["name2"] = "Straker2",     ["blocked"] = 0, ["taverna"] = 1, ["skill1"] =   7, ["skill2"] =  39, ["looser"] = 0, ["ver"] = 100, ["txt"] = "necropolis/heroOrson.txt",      ["p1"] = "hero_5_3_1", ["p2"] = "hero_5_3_2", ["p3"] = "hero_5_3_3", ["p4"] = "hero_5_3_4", ["p5"] = "hero_5_3_5", ["p6"] = "hero_5_3_6", ["p7"] = "hero_5_3_7", ["p8"] = "hero_5_3_8", ["block_temply"] = 0, ["dsc"] = "/Text/Game/Heroes/Specializations/Necropolis/Zombie_Leader/Description.txt" },
	  { ["name"] = "Effig",       ["name2"] = "Effig2",       ["blocked"] = 0, ["taverna"] = 1, ["skill1"] =  10, ["skill2"] =  46, ["looser"] = 0, ["ver"] = 100, ["txt"] = "necropolis/heroRavenna.txt",    ["p1"] = "hero_6_3_1", ["p2"] = "hero_6_3_2", ["p3"] = "hero_6_3_3", ["p4"] = "hero_6_3_4", ["p5"] = "hero_6_3_5", ["p6"] = "hero_6_3_6", ["p7"] = "hero_6_3_7", ["p8"] = "hero_6_3_8", ["block_temply"] = 0, ["dsc"] = "/Text/Game/Heroes/Specializations/Necropolis/Maledictor/Description.txt" },
	  { ["name"] = "Pelt",        ["name2"] = "Pelt2",        ["blocked"] = 0, ["taverna"] = 1, ["skill1"] =  12, ["skill2"] =  54, ["looser"] = 0, ["ver"] = 100, ["txt"] = "necropolis/heroVlad.txt",       ["p1"] = "hero_7_3_1", ["p2"] = "hero_7_3_2", ["p3"] = "hero_7_3_3", ["p4"] = "hero_7_3_4", ["p5"] = "hero_7_3_5", ["p6"] = "hero_7_3_6", ["p7"] = "hero_7_3_7", ["p8"] = "hero_7_3_8", ["block_temply"] = 0, ["dsc"] = "/Text/Game/Heroes/Specializations/Necropolis/Reanimator/Description.txt" },
	  { ["name"] = "Gles",        ["name2"] = "Gles2",        ["blocked"] = 0, ["taverna"] = 1, ["skill1"] =   2, ["skill2"] =  22, ["looser"] = 1, ["ver"] = 100, ["txt"] = "necropolis/heroKaspar.txt",     ["p1"] = "hero_8_3_1", ["p2"] = "hero_8_3_2", ["p3"] = "hero_8_3_3", ["p4"] = "hero_8_3_4", ["p5"] = "hero_8_3_5", ["p6"] = "hero_8_3_6", ["p7"] = "hero_8_3_7", ["p8"] = "hero_8_3_8", ["block_temply"] = 0, ["dsc"] = "/Text/Game/Heroes/Specializations/Necropolis/Empiric/Description.txt" },
	  { ["name"] = "Arantir",     ["name2"] = "Arantir2",     ["blocked"] = 0, ["taverna"] = 1, ["skill1"] =  12, ["skill2"] = 108, ["looser"] = 0, ["ver"] = 100, ["txt"] = "necropolis/heroArantir.txt",    ["p1"] = "hero_9_3_1", ["p2"] = "hero_9_3_2", ["p3"] = "hero_9_3_3", ["p4"] = "hero_9_3_4", ["p5"] = "hero_9_3_5", ["p6"] = "hero_9_3_6", ["p7"] = "hero_9_3_7", ["p8"] = "hero_9_3_8", ["block_temply"] = 0, ["dsc"] = "/Text/Game/Heroes/Specializations/Necropolis/AvatarOfDeath/Description.txt" },
	  { ["name"] = "OrnellaNecro",["name2"] = "OrnellaNecro2",["blocked"] = 0, ["taverna"] = 1, ["skill1"] =   4, ["skill2"] =  62, ["looser"] = 0, ["ver"] = 100, ["txt"] = "necropolis/heroOrnella.txt",    ["p1"] = "hero_10_3_1",["p2"] = "hero_10_3_2",["p3"] = "hero_10_3_3",["p4"] = "hero_10_3_4",["p5"] = "hero_10_3_5",["p6"] = "hero_10_3_6",["p7"] = "hero_10_3_7",["p8"] = "hero_10_3_8",["block_temply"] = 0, ["dsc"] = "/Text/Game/Heroes/Specializations/Necropolis/SpecOrnella/Description.txt" },
    { ["name"] = "Berein",      ["name2"] = "Berein2",      ["blocked"] = 0, ["taverna"] = 1, ["skill1"] =  15, ["skill2"] =  15, ["looser"] = 0, ["ver"] = 100, ["txt"] = "necropolis/heroMarkel.txt",     ["p1"] = "hero_11_3_1",["p2"] = "hero_11_3_2",["p3"] = "hero_11_3_3",["p4"] = "hero_11_3_4",["p5"] = "hero_11_3_5",["p6"] = "hero_11_3_6",["p7"] = "hero_11_3_7",["p8"] = "hero_11_3_8",["block_temply"] = 0, ["dsc"] = "/Text/Game/Heroes/Specializations/Necropolis/Heir_of_Undeath/Berein.txt" },
    { ["name"] = "Nikolas",     ["name2"] = "Nikolas2",     ["blocked"] = 0, ["taverna"] = 1, ["skill1"] =   3, ["skill2"] =   3, ["looser"] = 0, ["ver"] = 100, ["txt"] = "necropolis/heroNikolas.txt",    ["p1"] = "hero_12_3_1",["p2"] = "hero_12_3_2",["p3"] = "hero_12_3_3",["p4"] = "hero_12_3_4",["p5"] = "hero_12_3_5",["p6"] = "hero_12_3_6",["p7"] = "hero_12_3_7",["p8"] = "hero_12_3_8",["block_temply"] = 0, ["dsc"] = "/Text/Game/Heroes/Specializations/Necropolis/SpecNikolas/Description.txt" }
  },
  [RACES.SYLVAN] = {
	  { ["name"] = "Metlirn",     ["name2"] = "Metlirn2",     ["blocked"] = 0, ["taverna"] = 1, ["skill1"] =  16, ["skill2"] =  16, ["looser"] = 0, ["ver"] = 100, ["txt"] = "sylvan/heroAnven.txt",      ["p1"] = "hero_1_4_1", ["p2"] = "hero_1_4_2", ["p3"] = "hero_1_4_3", ["p4"] = "hero_1_4_4", ["p5"] = "hero_1_4_5", ["p6"] = "hero_1_4_6", ["p7"] = "hero_1_4_7", ["p8"] = "hero_1_4_8", ["block_temply"] = 0, ["dsc"] = "/Text/Game/Heroes/Specializations/Preserve/Forest_Guardian/Description.txt" },
	  { ["name"] = "Gillion",     ["name2"] = "Gillion2",     ["blocked"] = 0, ["taverna"] = 1, ["skill1"] =   7, ["skill2"] =  39, ["looser"] = 0, ["ver"] = 100, ["txt"] = "sylvan/heroGilraen.txt",    ["p1"] = "hero_2_4_1", ["p2"] = "hero_2_4_2", ["p3"] = "hero_2_4_3", ["p4"] = "hero_2_4_4", ["p5"] = "hero_2_4_5", ["p6"] = "hero_2_4_6", ["p7"] = "hero_2_4_7", ["p8"] = "hero_2_4_8", ["block_temply"] = 0, ["dsc"] = "/Text/Game/Heroes/Specializations/Preserve/Blade_Master/Description.txt" },
	  { ["name"] = "Nadaur",      ["name2"] = "Nadaur2",      ["blocked"] = 0, ["taverna"] = 1, ["skill1"] =   4, ["skill2"] =  28, ["looser"] = 1, ["ver"] = 100, ["txt"] = "sylvan/heroTalanar.txt",    ["p1"] = "hero_3_4_1", ["p2"] = "hero_3_4_2", ["p3"] = "hero_3_4_3", ["p4"] = "hero_3_4_4", ["p5"] = "hero_3_4_5", ["p6"] = "hero_3_4_6", ["p7"] = "hero_3_4_7", ["p8"] = "hero_3_4_8", ["block_temply"] = 0, ["dsc"] = "/Text/Game/Heroes/Specializations/Preserve/Elven_Fury/Description.txt" },
	  { ["name"] = "Diraya",      ["name2"] = "Diraya2",      ["blocked"] = 0, ["taverna"] = 1, ["skill1"] =  12, ["skill2"] =  53, ["looser"] = 1, ["ver"] = 100, ["txt"] = "sylvan/heroDirael.txt",     ["p1"] = "hero_4_4_1", ["p2"] = "hero_4_4_2", ["p3"] = "hero_4_4_3", ["p4"] = "hero_4_4_4", ["p5"] = "hero_4_4_5", ["p6"] = "hero_4_4_6", ["p7"] = "hero_4_4_7", ["p8"] = "hero_4_4_8", ["block_temply"] = 0, ["dsc"] = "/Text/Game/Heroes/Specializations/Preserve/Call_of_the_Wasp/Description.txt" },
	  { ["name"] = "Ossir",       ["name2"] = "Ossir2",       ["blocked"] = 0, ["taverna"] = 1, ["skill1"] =   5, ["skill2"] =  31, ["looser"] = 0, ["ver"] = 100, ["txt"] = "sylvan/heroOssir.txt",      ["p1"] = "hero_5_4_1", ["p2"] = "hero_5_4_2", ["p3"] = "hero_5_4_3", ["p4"] = "hero_5_4_4", ["p5"] = "hero_5_4_5", ["p6"] = "hero_5_4_6", ["p7"] = "hero_5_4_7", ["p8"] = "hero_5_4_8", ["block_temply"] = 0, ["dsc"] = "/Text/Game/Heroes/Specializations/Preserve/Hunter/Description.txt" },
	  { ["name"] = "Itil",        ["name2"] = "Itil2",        ["blocked"] = 0, ["taverna"] = 1, ["skill1"] =  11, ["skill2"] =  49, ["looser"] = 0, ["ver"] = 100, ["txt"] = "sylvan/heroIlfina.txt",     ["p1"] = "hero_6_4_1", ["p2"] = "hero_6_4_2", ["p3"] = "hero_6_4_3", ["p4"] = "hero_6_4_4", ["p5"] = "hero_6_4_5", ["p6"] = "hero_6_4_6", ["p7"] = "hero_6_4_7", ["p8"] = "hero_6_4_8", ["block_temply"] = 0, ["dsc"] = "/Text/Game/Heroes/Specializations/Preserve/Unicorn_Trainer/Description.txt" },
	  { ["name"] = "Elleshar",    ["name2"] = "Elleshar2",    ["blocked"] = 0, ["taverna"] = 1, ["skill1"] =   3, ["skill2"] =  25, ["looser"] = 0, ["ver"] = 100, ["txt"] = "sylvan/heroVinrael.txt",    ["p1"] = "hero_7_4_1", ["p2"] = "hero_7_4_2", ["p3"] = "hero_7_4_3", ["p4"] = "hero_7_4_4", ["p5"] = "hero_7_4_5", ["p6"] = "hero_7_4_6", ["p7"] = "hero_7_4_7", ["p8"] = "hero_7_4_8", ["block_temply"] = 0, ["dsc"] = "/Text/Game/Heroes/Specializations/Preserve/Talented_Warrior/Description.txt" },
	  { ["name"] = "Linaas",      ["name2"] = "Linaas2",      ["blocked"] = 0, ["taverna"] = 1, ["skill1"] =   6, ["skill2"] =  34, ["looser"] = 0, ["ver"] = 100, ["txt"] = "sylvan/heroVingael.txt",    ["p1"] = "hero_8_4_1", ["p2"] = "hero_8_4_2", ["p3"] = "hero_8_4_3", ["p4"] = "hero_8_4_4", ["p5"] = "hero_8_4_5", ["p6"] = "hero_8_4_6", ["p7"] = "hero_8_4_7", ["p8"] = "hero_8_4_8", ["block_temply"] = 0, ["dsc"] = "/Text/Game/Heroes/Specializations/Preserve/Waylayer/Description.txt" },
	  { ["name"] = "Heam",        ["name2"] = "Heam2",        ["blocked"] = 0, ["taverna"] = 1, ["skill1"] =   6, ["skill2"] =  35, ["looser"] = 1, ["ver"] = 100, ["txt"] = "sylvan/heroFaidaen.txt",    ["p1"] = "hero_9_4_1", ["p2"] = "hero_9_4_2", ["p3"] = "hero_9_4_3", ["p4"] = "hero_9_4_4", ["p5"] = "hero_9_4_5", ["p6"] = "hero_9_4_6", ["p7"] = "hero_9_4_7", ["p8"] = "hero_9_4_8", ["block_temply"] = 0, ["dsc"] = "/Text/Game/Heroes/Specializations/Preserve/Elven_Volley/Description.txt" },
	  { ["name"] = "Ildar",       ["name2"] = "Ildar2",       ["blocked"] = 0, ["taverna"] = 1, ["skill1"] =  11, ["skill2"] =  11, ["looser"] = 0, ["ver"] = 100, ["txt"] = "sylvan/heroAlaron.txt",     ["p1"] = "hero_10_4_1",["p2"] = "hero_10_4_2",["p3"] = "hero_10_4_3",["p4"] = "hero_10_4_4",["p5"] = "hero_10_4_5",["p6"] = "hero_10_4_6",["p7"] = "hero_10_4_7",["p8"] = "hero_10_4_8",["block_temply"] = 0, ["dsc"] = "/Text/Game/Heroes/Specializations/Preserve/SpecIldar/Description.txt" },
	  { ["name"] = "GhostFSLord", ["name2"] = "GhostFSLord2", ["blocked"] = 1, ["taverna"] = 1, ["skill1"] =   3, ["skill2"] =  12, ["looser"] = 0, ["ver"] = 100, ["txt"] = "sylvan/heroPrizrak.txt",    ["p1"] = "hero_11_4_1",["p2"] = "hero_11_4_2",["p3"] = "hero_11_4_3",["p4"] = "hero_11_4_4",["p5"] = "hero_11_4_5",["p6"] = "hero_11_4_6",["p7"] = "hero_11_4_7",["p8"] = "hero_11_4_8",["block_temply"] = 0, ["dsc"] = "/Text/Game/Heroes/Specializations/Preserve/Forest_Guardian/Description.txt" }
  },
  [RACES.ACADEMY] = {
	  { ["name"] = "Faiz",        ["name2"] = "Faiz2",        ["blocked"] = 0, ["taverna"] = 1, ["skill1"] =  10, ["skill2"] =  48, ["looser"] = 1, ["ver"] = 100, ["txt"] = "academy/heroFaiz.txt",       ["p1"] = "hero_1_5_1", ["p2"] = "hero_1_5_2", ["p3"] = "hero_1_5_3", ["p4"] = "hero_1_5_4", ["p5"] = "hero_1_5_5", ["p6"] = "hero_1_5_6", ["p7"] = "hero_1_5_7", ["p8"] = "hero_1_5_8", ["block_temply"] = 0, ["dsc"] = "/Text/Game/Heroes/Specializations/Academy/Disrupter/Description.txt" },
	  { ["name"] = "Havez",       ["name2"] = "Havez2",       ["blocked"] = 0, ["taverna"] = 1, ["skill1"] =   2, ["skill2"] =  68, ["looser"] = 0, ["ver"] = 100, ["txt"] = "academy/heroHafiz.txt",      ["p1"] = "hero_2_5_1", ["p2"] = "hero_2_5_2", ["p3"] = "hero_2_5_3", ["p4"] = "hero_2_5_4", ["p5"] = "hero_2_5_5", ["p6"] = "hero_2_5_6", ["p7"] = "hero_2_5_7", ["p8"] = "hero_2_5_8", ["block_temply"] = 0, ["dsc"] = "/Text/Game/Heroes/Specializations/Academy/Artisan/Description.txt" },
	  { ["name"] = "Nur",         ["name2"] = "Nur2",         ["blocked"] = 0, ["taverna"] = 1, ["skill1"] =   9, ["skill2"] =  44, ["looser"] = 0, ["ver"] = 100, ["txt"] = "academy/heroNazir.txt",      ["p1"] = "hero_3_5_1", ["p2"] = "hero_3_5_2", ["p3"] = "hero_3_5_3", ["p4"] = "hero_3_5_4", ["p5"] = "hero_3_5_5", ["p6"] = "hero_3_5_6", ["p7"] = "hero_3_5_7", ["p8"] = "hero_3_5_8", ["block_temply"] = 0, ["dsc"] = "/Text/Game/Heroes/Specializations/Academy/Weilder_of_Fire/Description.txt" },
	  { ["name"] = "Astral",      ["name2"] = "Astral2",      ["blocked"] = 0, ["taverna"] = 1, ["skill1"] =   8, ["skill2"] =  67, ["looser"] = 1, ["ver"] = 100, ["txt"] = "academy/heroNura.txt",       ["p1"] = "hero_4_5_1", ["p2"] = "hero_4_5_2", ["p3"] = "hero_4_5_3", ["p4"] = "hero_4_5_4", ["p5"] = "hero_4_5_5", ["p6"] = "hero_4_5_6", ["p7"] = "hero_4_5_7", ["p8"] = "hero_4_5_8", ["block_temply"] = 0, ["dsc"] = "/Text/Game/Heroes/Specializations/Academy/Inexhaustible/Description.txt" },
	  { ["name"] = "Sufi",        ["name2"] = "Sufi2",        ["blocked"] = 0, ["taverna"] = 1, ["skill1"] =   8, ["skill2"] =  42, ["looser"] = 0, ["ver"] = 100, ["txt"] = "academy/heroOra.txt",        ["p1"] = "hero_5_5_1", ["p2"] = "hero_5_5_2", ["p3"] = "hero_5_5_3", ["p4"] = "hero_5_5_4", ["p5"] = "hero_5_5_5", ["p6"] = "hero_5_5_6", ["p7"] = "hero_5_5_7", ["p8"] = "hero_5_5_8", ["block_temply"] = 0, ["dsc"] = "/Text/Game/Heroes/Specializations/Academy/Feather_Mage/Description.txt" },
	  { ["name"] = "Razzak",      ["name2"] = "Razzak2",      ["blocked"] = 0, ["taverna"] = 1, ["skill1"] =   3, ["skill2"] =  25, ["looser"] = 0, ["ver"] = 100, ["txt"] = "academy/heroNarhiz.txt",     ["p1"] = "hero_6_5_1", ["p2"] = "hero_6_5_2", ["p3"] = "hero_6_5_3", ["p4"] = "hero_6_5_4", ["p5"] = "hero_6_5_5", ["p6"] = "hero_6_5_6", ["p7"] = "hero_6_5_7", ["p8"] = "hero_6_5_8", ["block_temply"] = 0, ["dsc"] = "/Text/Game/Heroes/Specializations/Academy/Mentor/Description.txt" },
	  { ["name"] = "Tan",         ["name2"] = "Tan2",         ["blocked"] = 0, ["taverna"] = 1, ["skill1"] =   5, ["skill2"] =  69, ["looser"] = 1, ["ver"] = 100, ["txt"] = "academy/heroDgalib.txt",     ["p1"] = "hero_7_5_1", ["p2"] = "hero_7_5_2", ["p3"] = "hero_7_5_3", ["p4"] = "hero_7_5_4", ["p5"] = "hero_7_5_5", ["p6"] = "hero_7_5_6", ["p7"] = "hero_7_5_7", ["p8"] = "hero_7_5_8", ["block_temply"] = 0, ["dsc"] = "/Text/Game/Heroes/Specializations/Academy/Radiant/Description.txt" },
	  { ["name"] = "Isher",       ["name2"] = "Isher2",       ["blocked"] = 0, ["taverna"] = 1, ["skill1"] =   7, ["skill2"] =  39, ["looser"] = 0, ["ver"] = 100, ["txt"] = "academy/heroRazzak.txt",     ["p1"] = "hero_8_5_1", ["p2"] = "hero_8_5_2", ["p3"] = "hero_8_5_3", ["p4"] = "hero_8_5_4", ["p5"] = "hero_8_5_5", ["p6"] = "hero_8_5_6", ["p7"] = "hero_8_5_7", ["p8"] = "hero_8_5_8", ["block_temply"] = 0, ["dsc"] = "/Text/Game/Heroes/Specializations/Academy/Machinist/Description.txt" },
	  { ["name"] = "Zehir",       ["name2"] = "Zehir2",       ["blocked"] = 0, ["taverna"] = 1, ["skill1"] =  12, ["skill2"] =  53, ["looser"] = 0, ["ver"] = 100, ["txt"] = "academy/heroZehir.txt",      ["p1"] = "hero_9_5_1", ["p2"] = "hero_9_5_2", ["p3"] = "hero_9_5_3", ["p4"] = "hero_9_5_4", ["p5"] = "hero_9_5_5", ["p6"] = "hero_9_5_6", ["p7"] = "hero_9_5_7", ["p8"] = "hero_9_5_8", ["block_temply"] = 0, ["dsc"] = "/Text/Game/Heroes/Specializations/Academy/Master_of_Elements/Description.txt" },
	  { ["name"] = "Maahir",      ["name2"] = "Maahir2",      ["blocked"] = 0, ["taverna"] = 1, ["skill1"] =  17, ["skill2"] =  17, ["looser"] = 0, ["ver"] = 100, ["txt"] = "academy/heroMaahir.txt",     ["p1"] = "hero_10_5_1",["p2"] = "hero_10_5_2",["p3"] = "hero_10_5_3",["p4"] = "hero_10_5_4",["p5"] = "hero_10_5_5",["p6"] = "hero_10_5_6",["p7"] = "hero_10_5_7",["p8"] = "hero_10_5_8",["block_temply"] = 0, ["dsc"] = "/Text/Game/Heroes/Specializations/Academy/SpecMaahir/Description.txt" },
	  { ["name"] = "Cyrus",       ["name2"] = "Cyrus2",       ["blocked"] = 1, ["taverna"] = 1, ["skill1"] =  11, ["skill2"] =  11, ["looser"] = 0, ["ver"] = 100, ["txt"] = "academy/heroSairus.txt",     ["p1"] = "hero_11_5_1",["p2"] = "hero_11_5_2",["p3"] = "hero_11_5_3",["p4"] = "hero_11_5_4",["p5"] = "hero_11_5_5",["p6"] = "hero_11_5_6",["p7"] = "hero_11_5_7",["p8"] = "hero_11_5_8",["block_temply"] = 0, ["dsc"] = "/Text/Game/Heroes/Specializations/Academy/SpecCyrus/Description.txt" }
  },
  [RACES.DUNGEON] = {
	  { ["name"] = "Eruina",      ["name2"] = "Eruina2",      ["blocked"] = 0, ["taverna"] = 1, ["skill1"] =   6, ["skill2"] =   9, ["looser"] = 1, ["ver"] = 100, ["txt"] = "dungeon/heroErin.txt",       ["p1"] = "hero_1_6_1", ["p2"] = "hero_1_6_2", ["p3"] = "hero_1_6_3", ["p4"] = "hero_1_6_4", ["p5"] = "hero_1_6_5", ["p6"] = "hero_1_6_6", ["p7"] = "hero_1_6_7", ["p8"] = "hero_1_6_8", ["block_temply"] = 0, ["dsc"] = "/Text/Game/Heroes/Specializations/Dungeon/Matron_Salvo/Description.txt" },
	  { ["name"] = "Inagost",     ["name2"] = "Inagost2",     ["blocked"] = 0, ["taverna"] = 1, ["skill1"] =   9, ["skill2"] =  70, ["looser"] = 0, ["ver"] = 100, ["txt"] = "dungeon/heroSinitar.txt",    ["p1"] = "hero_2_6_1", ["p2"] = "hero_2_6_2", ["p3"] = "hero_2_6_3", ["p4"] = "hero_2_6_4", ["p5"] = "hero_2_6_5", ["p6"] = "hero_2_6_6", ["p7"] = "hero_2_6_7", ["p8"] = "hero_2_6_8", ["block_temply"] = 0, ["dsc"] = "/Text/Game/Heroes/Specializations/Dungeon/Power_Bargain/Description.txt" },
	  { ["name"] = "Urunir",      ["name2"] = "Urunir2",      ["blocked"] = 0, ["taverna"] = 1, ["skill1"] =   3, ["skill2"] =  25, ["looser"] = 0, ["ver"] = 100, ["txt"] = "dungeon/heroIranna.txt",     ["p1"] = "hero_3_6_1", ["p2"] = "hero_3_6_2", ["p3"] = "hero_3_6_3", ["p4"] = "hero_3_6_4", ["p5"] = "hero_3_6_5", ["p6"] = "hero_3_6_6", ["p7"] = "hero_3_6_7", ["p8"] = "hero_3_6_8", ["block_temply"] = 0, ["dsc"] = "/Text/Game/Heroes/Specializations/Dungeon/Seducer/Description.txt" },
	  { ["name"] = "Almegir",     ["name2"] = "Almegir2",     ["blocked"] = 0, ["taverna"] = 1, ["skill1"] =  12, ["skill2"] =  71, ["looser"] = 1, ["ver"] = 100, ["txt"] = "dungeon/heroIrbet.txt",      ["p1"] = "hero_4_6_1", ["p2"] = "hero_4_6_2", ["p3"] = "hero_4_6_3", ["p4"] = "hero_4_6_4", ["p5"] = "hero_4_6_5", ["p6"] = "hero_4_6_6", ["p7"] = "hero_4_6_7", ["p8"] = "hero_4_6_8", ["block_temply"] = 0, ["dsc"] = "/Text/Game/Heroes/Specializations/Dungeon/Dark_Acolyte/Description.txt" },
	  { ["name"] = "Menel",       ["name2"] = "Menel2",       ["blocked"] = 0, ["taverna"] = 1, ["skill1"] =   4, ["skill2"] =  29, ["looser"] = 0, ["ver"] = 100, ["txt"] = "dungeon/heroKifra.txt",      ["p1"] = "hero_5_6_1", ["p2"] = "hero_5_6_2", ["p3"] = "hero_5_6_3", ["p4"] = "hero_5_6_4", ["p5"] = "hero_5_6_5", ["p6"] = "hero_5_6_6", ["p7"] = "hero_5_6_7", ["p8"] = "hero_5_6_8", ["block_temply"] = 0, ["dsc"] = "/Text/Game/Heroes/Specializations/Dungeon/Slaveholder/Description.txt" },
	  { ["name"] = "Dalom",       ["name2"] = "Dalom2",       ["blocked"] = 0, ["taverna"] = 1, ["skill1"] =  10, ["skill2"] =  48, ["looser"] = 0, ["ver"] = 100, ["txt"] = "dungeon/heroLetos.txt",      ["p1"] = "hero_6_6_1", ["p2"] = "hero_6_6_2", ["p3"] = "hero_6_6_3", ["p4"] = "hero_6_6_4", ["p5"] = "hero_6_6_5", ["p6"] = "hero_6_6_6", ["p7"] = "hero_6_6_7", ["p8"] = "hero_6_6_8", ["block_temply"] = 0, ["dsc"] = "/Text/Game/Heroes/Specializations/Dungeon/Poisoner/Description.txt" },
	  { ["name"] = "Ferigl",      ["name2"] = "Ferigl2",      ["blocked"] = 0, ["taverna"] = 1, ["skill1"] =   6, ["skill2"] =  36, ["looser"] = 1, ["ver"] = 100, ["txt"] = "dungeon/heroSorgal.txt",     ["p1"] = "hero_7_6_1", ["p2"] = "hero_7_6_2", ["p3"] = "hero_7_6_3", ["p4"] = "hero_7_6_4", ["p5"] = "hero_7_6_5", ["p6"] = "hero_7_6_6", ["p7"] = "hero_7_6_7", ["p8"] = "hero_7_6_8", ["block_temply"] = 0, ["dsc"] = "/Text/Game/Heroes/Specializations/Dungeon/Lizard_Breeder/Description.txt" },
	  { ["name"] = "Ohtarig",     ["name2"] = "Ohtarig2",     ["blocked"] = 0, ["taverna"] = 1, ["skill1"] =   5, ["skill2"] =  32, ["looser"] = 0, ["ver"] = 100, ["txt"] = "dungeon/heroVaishan.txt",    ["p1"] = "hero_8_6_1", ["p2"] = "hero_8_6_2", ["p3"] = "hero_8_6_3", ["p4"] = "hero_8_6_4", ["p5"] = "hero_8_6_5", ["p6"] = "hero_8_6_6", ["p7"] = "hero_8_6_7", ["p8"] = "hero_8_6_8", ["block_temply"] = 0, ["dsc"] = "/Text/Game/Heroes/Specializations/Dungeon/Savage/Description.txt" },
	  { ["name"] = "Raelag_A1",   ["name2"] = "Raelag_A12",   ["blocked"] = 1, ["taverna"] = 1, ["skill1"] =   1, ["skill2"] =  18, ["looser"] = 0, ["ver"] = 100, ["txt"] = "dungeon/heroRailag.txt",     ["p1"] = "hero_9_6_1", ["p2"] = "hero_9_6_2", ["p3"] = "hero_9_6_3", ["p4"] = "hero_9_6_4", ["p5"] = "hero_9_6_5", ["p6"] = "hero_9_6_6", ["p7"] = "hero_9_6_7", ["p8"] = "hero_9_6_8", ["block_temply"] = 0, ["dsc"] = "/Text/Game/Heroes/Specializations/Dungeon/MasterOfInitiative/Description.txt" },
	  { ["name"] = "Kelodin",     ["name2"] = "Kelodin2",     ["blocked"] = 0, ["taverna"] = 1, ["skill1"] =   7, ["skill2"] =  38, ["looser"] = 0, ["ver"] = 100, ["txt"] = "dungeon/heroShadia.txt",     ["p1"] = "hero_10_6_1",["p2"] = "hero_10_6_2",["p3"] = "hero_10_6_3",["p4"] = "hero_10_6_4",["p5"] = "hero_10_6_5",["p6"] = "hero_10_6_6",["p7"] = "hero_10_6_7",["p8"] = "hero_10_6_8",["block_temply"] = 0, ["dsc"] = "/Text/Game/Heroes/Specializations/Dungeon/Evasive/Description.txt" },
	  { ["name"] = "Shadwyn",     ["name2"] = "Shadwyn2",     ["blocked"] = 0, ["taverna"] = 1, ["skill1"] =  18, ["skill2"] = 111, ["looser"] = 0, ["ver"] = 100, ["txt"] = "dungeon/heroIlaiya.txt",     ["p1"] = "hero_11_6_1",["p2"] = "hero_11_6_2",["p3"] = "hero_11_6_3",["p4"] = "hero_11_6_4",["p5"] = "hero_11_6_5",["p6"] = "hero_11_6_6",["p7"] = "hero_11_6_7",["p8"] = "hero_11_6_8",["block_temply"] = 0, ["dsc"] = "/Text/Game/Heroes/Specializations/Dungeon/SpecShadwyn/Description.txt" },
	  { ["name"] = "Thralsai",    ["name2"] = "Thralsai2",    ["blocked"] = 1, ["taverna"] = 1, ["skill1"] =   3, ["skill2"] =   3, ["looser"] = 0, ["ver"] = 100, ["txt"] = "dungeon/heroTralsai.txt",    ["p1"] = "hero_12_6_1",["p2"] = "hero_12_6_2",["p3"] = "hero_12_6_3",["p4"] = "hero_12_6_4",["p5"] = "hero_12_6_5",["p6"] = "hero_12_6_6",["p7"] = "hero_12_6_7",["p8"] = "hero_12_6_8",["block_temply"] = 0, ["dsc"] = "/Text/Game/Heroes/Specializations/Dungeon/SpecThralsai/Description.txt" }
  },
  [RACES.FORTRESS] = {
 	  { ["name"] = "Brand",       ["name2"] = "Brand2",       ["blocked"] = 0, ["taverna"] = 1, ["skill1"] = 151, ["skill2"] = 154, ["looser"] = 1, ["ver"] = 100, ["txt"] = "fortress/heroBrand.txt",      ["p1"] = "hero_1_7_1", ["p2"] = "hero_1_7_2", ["p3"] = "hero_1_7_3", ["p4"] = "hero_1_7_4", ["p5"] = "hero_1_7_5", ["p6"] = "hero_1_7_6", ["p7"] = "hero_1_7_7", ["p8"] = "hero_1_7_8", ["block_temply"] = 0, ["dsc"] = "/Text/Game/Heroes/Specializations/Fortress/Economist/Description.txt" },
	  { ["name"] = "Bersy",       ["name2"] = "Bersy2",       ["blocked"] = 0, ["taverna"] = 1, ["skill1"] =   6, ["skill2"] =  34, ["looser"] = 0, ["ver"] = 100, ["txt"] = "fortress/heroIbba.txt",       ["p1"] = "hero_2_7_1", ["p2"] = "hero_2_7_2", ["p3"] = "hero_2_7_3", ["p4"] = "hero_2_7_4", ["p5"] = "hero_2_7_5", ["p6"] = "hero_2_7_6", ["p7"] = "hero_2_7_7", ["p8"] = "hero_2_7_8", ["block_temply"] = 0, ["dsc"] = "/Text/Game/Heroes/Specializations/Fortress/Rider/Description.txt" },
	  { ["name"] = "Egil",        ["name2"] = "Egil2",        ["blocked"] = 0, ["taverna"] = 1, ["skill1"] =   8, ["skill2"] =   8, ["looser"] = 0, ["ver"] = 100, ["txt"] = "fortress/heroErling.txt",     ["p1"] = "hero_3_7_1", ["p2"] = "hero_3_7_2", ["p3"] = "hero_3_7_3", ["p4"] = "hero_3_7_4", ["p5"] = "hero_3_7_5", ["p6"] = "hero_3_7_6", ["p7"] = "hero_3_7_7", ["p8"] = "hero_3_7_8", ["block_temply"] = 0, ["dsc"] = "/Text/Game/Heroes/Specializations/Fortress/Magister/Description.txt" },
	  { ["name"] = "Ottar",       ["name2"] = "Ottar2",       ["blocked"] = 0, ["taverna"] = 1, ["skill1"] =  11, ["skill2"] =  11, ["looser"] = 0, ["ver"] = 100, ["txt"] = "fortress/heroHelmar.txt",     ["p1"] = "hero_4_7_1", ["p2"] = "hero_4_7_2", ["p3"] = "hero_4_7_3", ["p4"] = "hero_4_7_4", ["p5"] = "hero_4_7_5", ["p6"] = "hero_4_7_6", ["p7"] = "hero_4_7_7", ["p8"] = "hero_4_7_8", ["block_temply"] = 0, ["dsc"] = "/Text/Game/Heroes/Specializations/Fortress/Sacred_Hammer/Description.txt" },
	  { ["name"] = "Una",         ["name2"] = "Una2",         ["blocked"] = 0, ["taverna"] = 1, ["skill1"] =   3, ["skill2"] =  26, ["looser"] = 0, ["ver"] = 100, ["txt"] = "fortress/heroInga.txt",       ["p1"] = "hero_5_7_1", ["p2"] = "hero_5_7_2", ["p3"] = "hero_5_7_3", ["p4"] = "hero_5_7_4", ["p5"] = "hero_5_7_5", ["p6"] = "hero_5_7_6", ["p7"] = "hero_5_7_7", ["p8"] = "hero_5_7_8", ["block_temply"] = 0, ["dsc"] = "/Text/Game/Heroes/Specializations/Fortress/Researcher/Description.txt" },
	  { ["name"] = "Ingvar",      ["name2"] = "Ingvar2",      ["blocked"] = 0, ["taverna"] = 1, ["skill1"] =   7, ["skill2"] =  39, ["looser"] = 0, ["ver"] = 100, ["txt"] = "fortress/heroIngvar.txt",     ["p1"] = "hero_6_7_1", ["p2"] = "hero_6_7_2", ["p3"] = "hero_6_7_3", ["p4"] = "hero_6_7_4", ["p5"] = "hero_6_7_5", ["p6"] = "hero_6_7_6", ["p7"] = "hero_6_7_7", ["p8"] = "hero_6_7_8", ["block_temply"] = 0, ["dsc"] = "/Text/Game/Heroes/Specializations/Fortress/Defender/Description.txt" },
	  { ["name"] = "Vegeyr",      ["name2"] = "Vegeyr2",      ["blocked"] = 0, ["taverna"] = 1, ["skill1"] =   9, ["skill2"] =  45, ["looser"] = 1, ["ver"] = 100, ["txt"] = "fortress/heroSveya.txt",      ["p1"] = "hero_7_7_1", ["p2"] = "hero_7_7_2", ["p3"] = "hero_7_7_3", ["p4"] = "hero_7_7_4", ["p5"] = "hero_7_7_5", ["p6"] = "hero_7_7_6", ["p7"] = "hero_7_7_7", ["p8"] = "hero_7_7_8", ["block_temply"] = 0, ["dsc"] = "/Text/Game/Heroes/Specializations/Fortress/Stormcaller/Description.txt" },
	  { ["name"] = "Skeggy",      ["name2"] = "Skeggy2",      ["blocked"] = 0, ["taverna"] = 1, ["skill1"] =   5, ["skill2"] =  32, ["looser"] = 0, ["ver"] = 100, ["txt"] = "fortress/heroKarli.txt",      ["p1"] = "hero_8_7_1", ["p2"] = "hero_8_7_2", ["p3"] = "hero_8_7_3", ["p4"] = "hero_8_7_4", ["p5"] = "hero_8_7_5", ["p6"] = "hero_8_7_6", ["p7"] = "hero_8_7_7", ["p8"] = "hero_8_7_8", ["block_temply"] = 0, ["dsc"] = "/Text/Game/Heroes/Specializations/Fortress/Axe_Master/Description.txt" },
	  { ["name"] = "KingTolghar", ["name2"] = "KingTolghar2", ["blocked"] = 1, ["taverna"] = 1, ["skill1"] = 151, ["skill2"] = 151, ["looser"] = 0, ["ver"] = 100, ["txt"] = "fortress/heroTolgar.txt",     ["p1"] = "hero_9_7_1", ["p2"] = "hero_9_7_2", ["p3"] = "hero_9_7_3", ["p4"] = "hero_9_7_4", ["p5"] = "hero_9_7_5", ["p6"] = "hero_9_7_6", ["p7"] = "hero_9_7_7", ["p8"] = "hero_9_7_8", ["block_temply"] = 0, ["dsc"] = "/Text/Game/Heroes/Specializations/Fortress/Mountain_King/Description.txt" },
	  { ["name"] = "Wulfstan",    ["name2"] = "Wulfstan2",    ["blocked"] = 0, ["taverna"] = 1, ["skill1"] =   1, ["skill2"] =  19, ["looser"] = 0, ["ver"] = 100, ["txt"] = "fortress/heroVulfsten.txt",   ["p1"] = "hero_10_7_1",["p2"] = "hero_10_7_2",["p3"] = "hero_10_7_3",["p4"] = "hero_10_7_4",["p5"] = "hero_10_7_5",["p6"] = "hero_10_7_6",["p7"] = "hero_10_7_7",["p8"] = "hero_10_7_8",["block_temply"] = 0, ["dsc"] = "/Text/Game/Heroes/Specializations/Fortress/SpecWulfstan/Description.txt" },
	  { ["name"] = "Rolf",        ["name2"] = "Rolf2",        ["blocked"] = 0, ["taverna"] = 1, ["skill1"] =   4, ["skill2"] =  30, ["looser"] = 0, ["ver"] = 100, ["txt"] = "fortress/heroRolf.txt",       ["p1"] = "hero_11_7_1",["p2"] = "hero_11_7_2",["p3"] = "hero_11_7_3",["p4"] = "hero_11_7_4",["p5"] = "hero_11_7_5",["p6"] = "hero_11_7_6",["p7"] = "hero_11_7_7",["p8"] = "hero_11_7_8",["block_temply"] = 0, ["dsc"] = "/Text/Game/Heroes/Specializations/Fortress/SpecRolf/Description.txt" }
  },
  [RACES.STRONGHOLD] = {
	  { ["name"] = "Hero2",       ["name2"] = "Hero22",       ["blocked"] = 1, ["taverna"] = 1, ["skill1"] =   2, ["skill2"] =  22, ["looser"] = 1, ["ver"] = 100, ["txt"] = "stronghold/heroArgat.txt",      ["p1"] = "hero_1_8_1", ["p2"] = "hero_1_8_2", ["p3"] = "hero_1_8_3", ["p4"] = "hero_1_8_4", ["p5"] = "hero_1_8_5", ["p6"] = "hero_1_8_6", ["p7"] = "hero_1_8_7", ["p8"] = "hero_1_8_8", ["block_temply"] = 0, ["dsc"] = "/Text/Game/Heroes/Specializations/Stronghold/SpecArgat/Description.txt" },
	  { ["name"] = "Hero3",       ["name2"] = "Hero32",       ["blocked"] = 0, ["taverna"] = 1, ["skill1"] =   6, ["skill2"] =  36, ["looser"] = 0, ["ver"] = 100, ["txt"] = "stronghold/heroGaruna.txt",     ["p1"] = "hero_2_8_1", ["p2"] = "hero_2_8_2", ["p3"] = "hero_2_8_3", ["p4"] = "hero_2_8_4", ["p5"] = "hero_2_8_5", ["p6"] = "hero_2_8_6", ["p7"] = "hero_2_8_7", ["p8"] = "hero_2_8_8", ["block_temply"] = 0, ["dsc"] = "/Text/Game/Heroes/Specializations/Stronghold/Blooddrinker/Description.txt" },
	  { ["name"] = "Hero6",       ["name2"] = "Hero62",       ["blocked"] = 0, ["taverna"] = 1, ["skill1"] =   7, ["skill2"] =  39, ["looser"] = 0, ["ver"] = 100, ["txt"] = "stronghold/heroShakKarukat.txt",["p1"] = "hero_3_8_1", ["p2"] = "hero_3_8_2", ["p3"] = "hero_3_8_3", ["p4"] = "hero_3_8_4", ["p5"] = "hero_3_8_5", ["p6"] = "hero_3_8_6", ["p7"] = "hero_3_8_7", ["p8"] = "hero_3_8_8", ["block_temply"] = 0, ["dsc"] = "/Text/Game/Heroes/Specializations/Stronghold/SpecShak/Description.txt" },
	  { ["name"] = "Hero8",       ["name2"] = "Hero82",       ["blocked"] = 0, ["taverna"] = 1, ["skill1"] =   2, ["skill2"] = 173, ["looser"] = 0, ["ver"] = 100, ["txt"] = "stronghold/heroTilsek.txt",     ["p1"] = "hero_4_8_1", ["p2"] = "hero_4_8_2", ["p3"] = "hero_4_8_3", ["p4"] = "hero_4_8_4", ["p5"] = "hero_4_8_5", ["p6"] = "hero_4_8_6", ["p7"] = "hero_4_8_7", ["p8"] = "hero_4_8_8", ["block_temply"] = 0, ["dsc"] = "/Text/Game/Heroes/Specializations/Stronghold/GrimFighter/Description.txt" },
	  { ["name"] = "Hero7",       ["name2"] = "Hero72",       ["blocked"] = 0, ["taverna"] = 1, ["skill1"] =   6, ["skill2"] =  35, ["looser"] = 0, ["ver"] = 100, ["txt"] = "stronghold/heroHaggesh.txt",    ["p1"] = "hero_5_8_1", ["p2"] = "hero_5_8_2", ["p3"] = "hero_5_8_3", ["p4"] = "hero_5_8_4", ["p5"] = "hero_5_8_5", ["p6"] = "hero_5_8_6", ["p7"] = "hero_5_8_7", ["p8"] = "hero_5_8_8", ["block_temply"] = 0, ["dsc"] = "/Text/Game/Heroes/Specializations/Stronghold/CentaurMistress/Description.txt" },
 	  { ["name"] = "Hero1",       ["name2"] = "Hero12",       ["blocked"] = 0, ["taverna"] = 1, ["skill1"] =   6, ["skill2"] = 175, ["looser"] = 0, ["ver"] = 100, ["txt"] = "stronghold/heroKrag.txt",       ["p1"] = "hero_6_8_1", ["p2"] = "hero_6_8_2", ["p3"] = "hero_6_8_3", ["p4"] = "hero_6_8_4", ["p5"] = "hero_6_8_5", ["p6"] = "hero_6_8_6", ["p7"] = "hero_6_8_7", ["p8"] = "hero_6_8_8", ["block_temply"] = 0, ["dsc"] = "/Text/Game/Heroes/Specializations/Stronghold/Offender/Description.txt" },
 	  { ["name"] = "Hero9",       ["name2"] = "Hero92",       ["blocked"] = 0, ["taverna"] = 1, ["skill1"] =   4, ["skill2"] =  28, ["looser"] = 1, ["ver"] = 100, ["txt"] = "stronghold/heroKigan.txt",      ["p1"] = "hero_7_8_1", ["p2"] = "hero_7_8_2", ["p3"] = "hero_7_8_3", ["p4"] = "hero_7_8_4", ["p5"] = "hero_7_8_5", ["p6"] = "hero_7_8_6", ["p7"] = "hero_7_8_7", ["p8"] = "hero_7_8_8", ["block_temply"] = 0, ["dsc"] = "/Text/Game/Heroes/Specializations/Stronghold/GoblinKing/Description.txt" },
	  { ["name"] = "Hero4",       ["name2"] = "Hero42",       ["blocked"] = 0, ["taverna"] = 1, ["skill1"] = 172, ["skill2"] = 175, ["looser"] = 0, ["ver"] = 100, ["txt"] = "stronghold/heroGoshak.txt",     ["p1"] = "hero_8_8_1", ["p2"] = "hero_8_8_2", ["p3"] = "hero_8_8_3", ["p4"] = "hero_8_8_4", ["p5"] = "hero_8_8_5", ["p6"] = "hero_8_8_6", ["p7"] = "hero_8_8_7", ["p8"] = "hero_8_8_8", ["block_temply"] = 0, ["dsc"] = "/Text/Game/Heroes/Specializations/Stronghold/OrcElder/Description.txt" },
	  { ["name"] = "Kujin",       ["name2"] = "Kujin2",       ["blocked"] = 0, ["taverna"] = 1, ["skill1"] = 183, ["skill2"] = 174, ["looser"] = 0, ["ver"] = 100, ["txt"] = "stronghold/heroKudgin.txt",     ["p1"] = "hero_9_8_1", ["p2"] = "hero_9_8_2", ["p3"] = "hero_9_8_3", ["p4"] = "hero_9_8_4", ["p5"] = "hero_9_8_5", ["p6"] = "hero_9_8_6", ["p7"] = "hero_9_8_7", ["p8"] = "hero_9_8_8", ["block_temply"] = 0, ["dsc"] = "/Text/Game/Heroes/Specializations/Stronghold/SpecKujin/Description.txt" },
	  { ["name"] = "Gottai",      ["name2"] = "Gottai2",      ["blocked"] = 0, ["taverna"] = 1, ["skill1"] = 172, ["skill2"] = 187, ["looser"] = 0, ["ver"] = 100, ["txt"] = "stronghold/heroGotai.txt",      ["p1"] = "hero_10_8_1",["p2"] = "hero_10_8_2",["p3"] = "hero_10_8_3",["p4"] = "hero_10_8_4",["p5"] = "hero_10_8_5",["p6"] = "hero_10_8_6",["p7"] = "hero_10_8_7",["p8"] = "hero_10_8_8",["block_temply"] = 0, ["dsc"] = "/Text/Game/Heroes/Specializations/Stronghold/WarLeader/Description.txt" },
	  { ["name"] = "Quroq",       ["name2"] = "Quroq2",       ["blocked"] = 0, ["taverna"] = 1, ["skill1"] = 187, ["skill2"] = 190, ["looser"] = 0, ["ver"] = 100, ["txt"] = "stronghold/heroKurak.txt",      ["p1"] = "hero_11_8_1",["p2"] = "hero_11_8_2",["p3"] = "hero_11_8_3",["p4"] = "hero_11_8_4",["p5"] = "hero_11_8_5",["p6"] = "hero_11_8_6",["p7"] = "hero_11_8_7",["p8"] = "hero_11_8_8",["block_temply"] = 0, ["dsc"] = "/Text/Game/Heroes/Specializations/Stronghold/SpecQuroq/Description.txt" }
  }
};
