# Half-RTA deploy
name: deploy

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  MAP_VER: Half-RTA_1.26f

jobs:     
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - working-directory: ./Half-RTA
      run: pwd
    - name: Raname Dir
      working-directory: ./Half-RTA/
      run: mv Maps/Multiplayer/Half-RTA Maps/Multiplayer/$MAP_VER
    - name: Zip Map
      working-directory: ./Half-RTA
      run: zip -r ${{ env.MAP_VER }}.h5m .
    - run: mkdir -p path/to/artifact
    - name: Copy Map
      run: cp -r Half-RTA/${{ env.MAP_VER }}.h5m path/to/artifact
    #- name: Copy Exe
    #  run: cp -r Exe/H5_Game.exe path/to/artifact
    - name: Get version
      working-directory: ./Half-RTA/Maps/Multiplayer/Half-RTA/messages
      id: vars
      run: echo ::set-output name=version::$(awk 'END {print $NF}' file map_name.txt)
    - name: Test output
      run: echo ${{ steps.vars.outputs.version }}
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ env.MAP_VER }}
        path: path/to/artifact/
